#!/usr/bin/env python3
"""
Assigns difficulty (1=easy, 2=medium, 3=hard) to A2-level German vocabulary.
Criteria (relative to A2):
  1 = easy: very frequent, short, beginner-first, basic grammar words
  2 = medium: typical A2 vocabulary, moderate length/complexity
  3 = hard: compound words, separable/reflexive verbs, abstract, administrative,
             less common at A2, or long words
Distribution target: roughly even thirds (~353 each).
"""
import csv

# Explicit overrides: word -> difficulty
# Python dicts keep the last value for duplicate keys.
OVERRIDES = {

    # ---- ABBREVIATIONS / ANWEISUNGSSPRACHE ----
    'ca.': 1, 'd.h.': 1, 'ICE': 2, 'Lkw': 2, 'PC': 1,
    'SMS': 1, 'usw.': 1, 'WC': 1, 'z.B.': 1,
    'Abkürzung': 2,
    'Anweisungssprache': 3,
    'Antwortbogen': 3, 'Aufgabe': 2, 'Beispiel': 1, 'Durchsage': 3,
    'Lösung': 2, 'markieren': 2, 'Prüfer': 2, 'Prüferin': 2,
    'Prüfung': 2, 'Punkt': 1, 'Teil': 1, 'Test': 1,
    'Text': 1, 'Wörterbuch': 3,

    # ---- BERUFE (professions) ----
    'Beruf': 2,
    'Angestellte': 3,
    'Arzt': 2, 'Ärztin': 2,
    'Auszubildende': 3,
    'Autor': 2, 'Autorin': 2,
    'Babysitter': 2,
    'Bäcker': 2, 'Bäckerin': 2,
    'Doktor': 1, 'Doktorin': 2,
    'Fahrer': 2, 'Fahrerin': 2,
    'Friseur': 2, 'Friseurin': 2,
    'Handwerker': 3, 'Handwerkerin': 3,
    'Hausmann': 2, 'Hausfrau': 2,
    'Journalist': 3, 'Journalistin': 3,
    'Kaufmann': 3, 'Kauffrau': 3,
    'Kellner': 2, 'Kellnerin': 2,
    'Koch': 1, 'Köchin': 2,
    'Krankenpfleger': 3, 'Krankenschwester': 3,
    'Künstler': 2, 'Künstlerin': 2,
    'Lehrer': 1, 'Lehrerin': 1,
    'Mechaniker': 2, 'Mechanikerin': 2,
    'Model': 1,
    'Musiker': 2, 'Musikerin': 2,
    'Polizist': 2, 'Polizistin': 2,
    'Rentner': 2, 'Rentnerin': 2,
    'Sänger': 2, 'Sängerin': 2,
    'Schauspieler': 3, 'Schauspielerin': 3,
    'Techniker': 2, 'Technikerin': 2,
    'Verkäufer': 2, 'Verkäuferin': 2,

    # ---- FAMILIENMITGLIEDER ----
    'Familienmitglied': 3,
    'Bruder': 1,
    'Cousin': 2, 'Cousine': 2,
    'Eltern': 1,
    'Enkel': 2, 'Enkelin': 2,
    'Geschwister': 2,
    'Großeltern': 3,
    'Großmutter': 2, 'Oma': 1,
    'Großvater': 2, 'Opa': 1,
    'Kind': 1,
    'Mutter': 1, 'Mama': 1,
    'Onkel': 1,
    'Schwester': 1,
    'Sohn': 1,
    'Tante': 1,
    'Tochter': 1,
    'Vater': 1, 'Papa': 1,
    'Verwandte': 2,

    # ---- FAMILIENSTAND ----
    'Familienstand': 3,
    'ledig': 2, 'verheiratet': 2, 'getrennt': 2, 'geschieden': 3,

    # ---- FARBEN ----
    'Farbe': 1,
    'blau': 1, 'braun': 1, 'gelb': 1, 'grau': 1, 'grün': 1,
    'lila': 2, 'orange': 1, 'rosa': 1, 'rot': 1,
    'schwarz': 1, 'weiß': 1,

    # ---- HIMMELSRICHTUNGEN ----
    'Himmelsrichtung': 3,
    'Norden': 2, 'Süden': 2, 'Osten': 2, 'Westen': 2,

    # ---- LÄNDER / NATIONALITÄTEN ----
    'Land': 1, 'Nationalität': 3,
    'Deutschland': 1, 'Deutsche': 1, 'deutsch': 1,
    'Österreich': 2, 'Österreicher': 3, 'Österreicherin': 3, 'österreichisch': 3,
    'Schweiz': 2, 'Schweizer': 2, 'Schweizerin': 2, 'schweizerisch': 3,
    'Luxemburg': 2, 'Luxemburger': 3, 'Luxemburgerin': 3, 'luxemburgisch': 3,
    'Europa': 1, 'Europäer': 2, 'Europäerin': 2, 'europäisch': 2,

    # ---- WÄHRUNGEN / MASSE ----
    'Währung': 3, 'Maß': 2,
    'Euro': 1, 'Cent': 1,
    'Franken': 2, 'Rappen': 3,
    'Meter': 1, 'Zentimeter': 2, 'Kilometer': 2,
    'Prozent': 2, 'Liter': 2, 'Gramm': 2, 'Kilogramm': 2,
    'Grad': 2,

    # ---- SCHULE / SCHULFÄCHER ----
    'Schule': 1, 'Schulfach': 3,
    'Abitur': 3,
    'Direktor': 2,
    'Hausaufgabe': 3,
    'Klasse': 1,
    'Klassenfahrt': 3,
    'Sekretariat': 3,
    'Stundenplan': 3,
    'Biologie': 2, 'Chemie': 2,
    'Deutsch': 1, 'Englisch': 1,
    'Französisch': 2,
    'Geografie': 2, 'Geschichte': 2,
    'Kunst': 1,
    'Latein': 3,
    'Mathematik': 2,
    'Musik': 1,
    'Physik': 2,
    'Religion': 2,
    'Sozialkunde': 3,
    'Sport': 1,

    # ---- FEIERTAGE ----
    'Feiertag': 2,
    'Karneval': 2, 'Ostern': 2, 'Weihnachten': 2,
    'Neujahr': 2, 'Silvester': 2,

    # ---- JAHRESZEITEN ----
    'Jahreszeit': 3,
    'Frühling': 2, 'Frühjahr': 2,
    'Sommer': 1, 'Herbst': 2, 'Winter': 1,

    # ---- MONATE ----
    'Monat': 2,
    'Januar': 2, 'Februar': 3, 'März': 1, 'April': 1,
    'Mai': 1, 'Juni': 1, 'Juli': 1, 'August': 1,
    'September': 2, 'Oktober': 2, 'November': 2, 'Dezember': 3,

    # ---- TAGESZEITEN ----
    'Tageszeit': 3,
    'Tag': 1, 'Morgen': 1, 'Vormittag': 3, 'Mittag': 2,
    'Nachmittag': 3, 'Abend': 1, 'Nacht': 1, 'Mitternacht': 3,
    'täglich': 2, 'tagsüber': 2,
    'morgens': 2, 'vormittags': 3, 'mittags': 2,
    'nachmittags': 3, 'abends': 2, 'nachts': 2,

    # ---- ZAHLEN ----
    'Zahlen': 1,
    'eins': 1, 'zwei': 1, 'drei': 1, 'vier': 1, 'fünf': 1,
    'sechs': 1, 'sieben': 1, 'acht': 1, 'neun': 1, 'zehn': 1,
    'elf': 1, 'zwölf': 1,
    'dreizehn': 2, 'vierzehn': 2, 'fünfzehn': 2, 'sechzehn': 2,
    'siebzehn': 2, 'achtzehn': 2, 'neunzehn': 2,
    'zwanzig': 2, 'einundzwanzig': 3,
    'dreißig': 2, 'vierzig': 2, 'fünfzig': 2, 'sechzig': 2,
    'siebzig': 2, 'achtzig': 2, 'neunzig': 2,
    'hundert': 2, 'hunderteins': 3, 'zweihundert': 3,
    'tausend': 2, 'zweitausendeins': 3,
    'Million': 3,
    'erste': 2, 'zweite': 2, 'dritte': 2, 'vierte': 2,
    'erstens': 3, 'zweitens': 3, 'drittens': 3, 'viertens': 3,
    'einmal': 1, 'zweimal': 2, 'dreimal': 2, 'viermal': 2,

    # ---- UHRZEIT ----
    'Uhrzeit': 2,
    'Sekunde': 2, 'Minute': 1, 'Stunde': 1,

    # ---- WOCHENTAGE ----
    'Wochentag': 2, 'Wochenende': 2,
    'Montag': 2, 'Dienstag': 3, 'Mittwoch': 2, 'Donnerstag': 3,
    'Freitag': 2, 'Samstag': 2, 'Sonntag': 2,
    'montags': 2, 'dienstags': 3, 'mittwochs': 2, 'donnerstags': 3,
    'freitags': 2, 'samstags': 2, 'sonntags': 2,
    'Arbeitstag': 3, 'Werktag': 2,
    'Woche': 1, 'Jahr': 1,

    # ---- ALPHABETICAL SECTION A ----
    'Angebot': 2,
    'ändern': 2,
    'anders': 2,
    'anfangen': 2,
    'Anfang': 1,
    'Angst': 1,
    'ankommen': 1,
    'anmachen': 2,
    'anmelden': 3,
    'Anmeldung': 3,
    'anrufen': 1,
    'Anruf': 1,
    'ansehen': 3,
    'antworten': 1,
    'Anzeige': 3,
    'abgeben': 3,
    'abholen': 3,
    'abschließen': 3,
    'Adresse': 2,
    'aktiv': 2,
    'als': 1,
    'alt': 1,
    'Alter': 2,
    'an': 1,
    'anbieten': 3,
    'aus': 1,
    'Ausbildung': 3,
    'Ausflug': 3,
    'ausfüllen': 3,
    'Ausgang': 3,
    'ausgehen': 2,
    'Auskunft': 3,
    'Ausland': 3,
    'auspacken': 3,
    'ausruhen': 3,
    'aussehen': 1,
    'außer': 3,
    'aussprechen': 3,
    'aussteigen': 3,
    'Ausstellung': 3,
    'Ausweis': 3,
    'Auto': 1,
    'arbeiten': 1,
    'Arbeit': 1,
    'ärgern': 3,
    'auch': 1,
    'auf': 1,
    'aufhören': 3,
    'aufmachen': 2,
    'aufpassen': 3,
    'aufräumen': 3,
    'aufregend': 3,
    'aufstehen': 3,
    'Aufzug': 3,
    'Auge': 1,

    # ---- ALPHABETICAL SECTION B ----
    'Baby': 1,
    'backen': 3,
    'Bäckerei': 3,
    'baden': 2,
    'Bahn': 1,
    'Bahnhof': 3,
    'Balkon': 2,
    'Bank': 2,
    'Bauch': 2,
    'Baum': 2,
    'Baustelle': 3,
    'bedanken': 3,
    'bedeuten': 3,
    'beeilen': 3,
    'beenden': 3,
    'beginnen': 2,
    'begründen': 3,
    'bei': 1,
    'beide': 2,
    'Bein': 2,
    'bekannt': 2,
    'bekommen': 2,
    'bequem': 3,
    'beraten': 3,
    'Berg': 1,
    'berichten': 3,
    'beschreiben': 3,
    'beschweren': 3,
    'besonders': 2,
    'bestätigen': 3,
    'bestehen': 3,
    'bestellen': 1,
    'Besuch': 1,
    'besuchen': 1,
    'Bett': 1,
    'bewölkt': 3,
    'bezahlen': 2,
    'Bibliothek': 3,
    'Bild': 1,
    'Birne': 3,
    'bisschen': 1,
    'bitte': 1,
    'Bitte': 2,
    'bleiben': 1,
    'Bleistift': 3,
    'braten': 2,
    'brauchen': 1,
    'Brief': 1,
    'bringen': 1,
    'Brot': 1,
    'Brötchen': 1,
    'Buch': 1,
    'buchen': 3,
    'Buchstabe': 3,
    'bunt': 2,
    'Büro': 1,
    'Bus': 1,

    # ---- ALPHABETICAL SECTION C ----
    'Café': 1,
    'Cafeteria': 2,
    'chatten': 3,
    'Chef': 2,
    'Chefin': 2,
    'Club': 2,
    'Computer': 1,

    # ---- ALPHABETICAL SECTION D ----
    'da': 1,
    'dafür': 2,
    'dagegen': 2,
    'damals': 2,
    'Dame': 2,
    'daneben': 3,
    'Dank': 2,
    'danken': 2,
    'Datei': 2,
    'Datum': 1,
    'dauern': 1,
    'denken': 1,
    'deshalb': 2,
    'deutlich': 2,
    'dick': 1,
    'Ding': 1,
    'direkt': 2,
    'Disco': 2,
    'diskutieren': 3,
    'Doppelzimmer': 3,
    'Dorf': 2,
    'draußen': 2,
    'dringend': 2,
    'drinnen': 2,
    'drüben': 3,
    'Drucker': 2,
    'dunkel': 2,
    'dünn': 2,
    'durch': 1,
    'dürfen': 1,
    'Durst': 2,

    # ---- ALPHABETICAL SECTION E ----
    'E-Book': 2,
    'echt': 2,
    'Ecke': 2,
    'egal': 2,
    'Ehefrau': 2,
    'Ehemann': 2,
    'Ei': 1,
    'eilig': 2,
    'Eingang': 2,
    'einkaufen': 2,
    'Einkaufs-': 2,
    'einladen': 3,
    'Einladung': 3,
    'einpacken': 3,
    'einsteigen': 3,
    'eintragen': 3,
    'Eintritt': 3,
    'einverstanden': 3,
    'einzel-': 2,
    'einziehen': 3,
    'Eis': 1,
    'empfehlen': 3,
    'Ende': 1,
    'enden': 2,
    'endlich': 2,
    'eng': 2,
    'entschuldigen': 3,
    'Entschuldi-': 3,
    'Erfahrung': 3,
    'erklären': 3,
    'erlauben': 3,
    'Erlaubnis': 3,
    'erreichen': 3,
    'erst': 2,
    'Erwachsene': 3,
    'erzählen': 3,
    'essen': 1,
    'Essen': 1,
    'etwas': 1,

    # ---- ALPHABETICAL SECTION F ----
    'Fach': 2,
    'Abfahrt': 3,
    'Fahrplan': 3,
    'falsch': 1,
    'Familie': 1,
    'Familien-': 2,
    'Fan': 2,
    'fantastisch': 3,
    'fast': 2,
    'faul': 2,
    'fehlen': 3,
    'Fehler': 1,
    'feiern': 1,
    'Fenster': 1,
    'fernsehen': 3,
    'Fernseher': 2,
    'Fest': 1,
    'Festival': 3,
    'Firma': 2,
    'Fleisch': 1,
    'Flohmarkt': 3,
    'Flug': 2,
    'Flughafen': 3,
    'Fluss': 1,
    'Foto': 1,
    'Frau': 1,
    'freiwillig': 3,
    'freuen': 1,
    'Freund': 1,
    'Freundin': 1,
    'freundlich': 1,
    'frisch': 1,
    'früh': 1,
    'früher': 1,
    'Frühstück': 1,
    'fühlen': 1,
    'Führerschein': 3,
    'Führung': 3,
    'für': 1,
    'furchtbar': 3,
    'Fuß': 1,
    'Fußball': 1,

    # ---- ALPHABETICAL SECTION G ----
    'Gabel': 1,
    'Garage': 1,
    'geboren': 1,
    'gefallen': 1,
    'gegen': 1,
    'Gehalt': 3,
    'gehören': 3,
    'Geld': 1,
    'Geldbörse': 3,
    'genug': 1,
    'Gepäck': 1,
    'gerade': 2,
    'Geschäft': 1,
    'Geschirr': 2,
    'Gespräch': 1,
    'gestern': 1,
    'Getränk': 1,
    'gewinnen': 3,
    'Gewitter': 3,
    'glauben': 1,
    'gleich': 1,
    'Gleis': 3,
    'glücklich': 1,
    'gratulieren': 3,
    'grillen': 3,
    'Grippe': 2,
    'groß': 1,
    'Größe': 1,
    'Gruß': 2,
    'günstig': 3,

    # ---- ALPHABETICAL SECTION H ----
    'Haar': 1,
    'Hähnchen': 3,
    'hallo': 1,
    'Hals': 3,
    'halten': 3,
    'Haltestelle': 3,
    'hängen': 3,
    'hart': 2,
    'hässlich': 3,
    'Hauptstadt': 3,
    'Haushalt': 3,
    'Heft': 3,
    'Heimat': 3,
    'heiraten': 1,
    'heißen': 1,
    'Heizung': 3,
    'hell': 2,
    'Hemd': 3,
    'her': 2,
    'heraus': 2,
    'herein': 2,
    'hinter': 2,
    'hinten': 2,
    'Hobby': 1,
    'Hochzeit': 1,
    'hoffen': 1,
    'Homepage': 3,
    'hören': 1,
    'Hose': 1,
    'Hunger': 1,
    'herunterladen': 3,
    'herzlich': 3,
    'Hilfe': 1,
    'Himmel': 3,
    'hin': 3,
    'Herr': 1,
    'Herd': 2,
    'rein': 2,
    'raus': 2,

    # ---- ALPHABETICAL SECTION I/J/K ----
    'Ich': 1,
    'immer': 1,
    'Information': 2,
    'informieren': 3,
    'Insel': 2,
    'Instrument': 2,
    'interessant': 3,
    'interessieren': 3,
    'international': 3,
    'Internet': 1,
    'Interview': 3,
    'ja': 1,
    'Jacke': 1,
    'jemand': 1,
    'joggen': 2,
    'jung': 1,
    'Junge': 1,
    'Jugend-': 2,
    'Kaffee': 1,
    'Kalender': 2,
    'kalt': 1,
    'Kamera': 3,
    'Kartoffel': 3,
    'Kaufhaus': 3,
    'Keller': 3,
    'kennen': 1,
    'kennenlernen': 3,
    'Kenntnisse': 3,
    'Kette': 3,
    'Kirche': 3,
    'Klavier': 3,
    'Kleid': 3,
    'klein': 1,
    'klug': 3,
    'kochen': 1,
    'Koffer': 3,
    'Kollegin': 3,
    'komisch': 2,
    'kommen': 1,
    'können': 1,
    'Kontakt': 3,
    'Konto': 3,
    'kontrollieren': 3,
    'Konzert': 3,
    'Kopf': 1,
    'Kosmetik': 3,
    'kostenlos': 2,
    'krank': 1,
    'Kranken-': 3,
    'Krankheit': 3,
    'Kreuzung': 3,
    'Krimi': 3,
    'Küche': 1,
    'Kuchen': 1,
    'Kühl-': 3,
    'Kultur': 3,
    'kümmern': 3,
    'Kunde': 3,
    'Kundin': 3,
    'kündigen': 3,
    'Kurs': 3,

    # ---- ALPHABETICAL SECTION L ----
    'lachen': 1,
    'Laden': 1,
    'Lampe': 1,
    'Landschaft': 3,
    'lange': 2,
    'laufen': 1,
    'Leben': 1,
    'leihen': 3,
    'lesen': 1,
    'letzt-': 2,
    'Leute': 1,
    'lieben': 1,
    'liegen': 1,
    'Link': 3,
    'Lust': 3,
    'lustig': 1,

    # ---- ALPHABETICAL SECTION M ----
    'machen': 1,
    'Mädchen': 1,
    'Magen': 3,
    'malen': 3,
    'man': 1,
    'manch-': 3,
    'Mann': 1,
    'Maschine': 3,
    'meinen': 3,
    'Meinung': 3,
    'Mensch': 1,
    'merken': 3,
    'Messe': 3,
    'Messer': 3,
    'Miete': 3,
    'mieten': 3,
    'Milch': 1,
    'Mineral-': 2,
    'mit': 1,
    'Mitarbeiter': 3,
    'mittel': 2,
    'Mittel': 2,
    'Mittagessen': 3,
    'Möbel': 2,
    'Mobil-': 2,
    'möchten': 1,
    'Mode': 1,
    'möglich': 3,
    'meist-': 2,
    'Moment': 1,
    'morgen': 1,
    'Motor': 3,
    'Mund': 1,
    'Museum': 1,
    'müssen': 1,
    'musste': 2,
    'Mütze': 3,

    # ---- ALPHABETICAL SECTION N ----
    'nach': 1,
    'Nachbar': 3,
    'Nachricht': 3,
    'Nähe': 3,
    'Name': 1,
    'nass': 2,
    'Natur': 1,
    'natürlich': 1,
    'neben': 1,
    'nennen': 2,
    'nervös': 3,
    'neu': 1,
    'nicht': 1,
    'nichts': 1,
    'nie': 1,
    'niemand': 2,
    'nirgends': 3,
    'noch': 1,
    'normal': 2,
    'Note': 3,
    'Notiz': 3,
    'Nudel': 1,
    'Nummer': 1,
    'nur': 1,
    'nützlich': 3,

    # ---- ALPHABETICAL SECTION O/Ö ----
    'oben': 2,
    'oder': 1,
    'offen': 1,
    'öffnen': 1,
    'oft': 1,
    'Ohr': 1,
    'Öl': 2,
    'online': 1,
    'Orange': 1,
    'Ordnung': 3,
    'organisieren': 3,
    'Ort': 1,

    # ---- ALPHABETICAL SECTION P/Q ----
    'Paar': 1,
    'packen': 2,
    'Paket': 3,
    'Partner': 3,
    'Partnerin': 3,
    'Party': 1,
    'passieren': 1,
    'Pause': 1,
    'Person': 1,
    'Pizza': 1,
    'Plakat': 3,
    'Plan': 2,
    'Platz': 1,
    'plötzlich': 3,
    'Polizei': 2,
    'Portion': 3,
    'Poster': 2,
    'Praktikum': 3,
    'Praxis': 3,
    'Preis': 2,
    'preiswert': 3,
    'pro': 1,
    'probieren': 2,
    'Problem': 1,
    'Projekt': 3,
    'Prospekt': 3,
    'prüfen': 2,
    'putzen': 2,
    'Qualität': 3,
    'Quiz': 2,

    # ---- ALPHABETICAL SECTION R ----
    'Radio': 1,
    'Rathaus': 3,
    'Rätsel': 3,
    'rauchen': 2,
    'Raum': 3,
    'Rechnung': 3,
    'Regen': 1,
    'Reinigung': 3,
    'Reise': 2,
    'Reisebüro': 3,
    'Reiseführer': 3,
    'reisen': 2,
    'reiten': 3,
    'renovieren': 3,
    'Reparatur': 3,
    'reservieren': 2,
    'Rest': 2,
    'Restaurant': 1,
    'Rezeption': 3,
    'richtig': 1,
    'riechen': 3,
    'Rind': 3,
    'Rose': 1,
    'Rücken': 1,
    'rufen': 2,
    'Ruhe': 1,
    'ruhig': 1,
    'rund': 2,
    'Rundgang': 3,

    # ---- ALPHABETICAL SECTION S ----
    'Sache': 2,
    'Saft': 2,
    'sagen': 1,
    'Salat': 1,
    'Salz': 1,
    'sammeln': 2,
    'Satz': 3,
    'Schalter': 3,
    'scharf': 2,
    'scheinen': 2,
    'schenken': 2,
    'Schere': 2,
    'schicken': 2,
    'Schiff': 2,
    'Schirm': 2,
    'schlecht': 1,
    'schließen': 2,
    'Schluss': 2,
    'Schlüssel': 2,
    'schmecken': 2,
    'Schmerz': 2,
    'schneien': 2,
    'schnell': 1,
    'schon': 1,
    'schön': 1,
    'Schrank': 2,
    'schrecklich': 2,
    'schreiben': 1,
    'schriftlich': 3,
    'Schuh': 1,
    'Schüler': 2,
    'Schülerin': 2,
    'schwach': 1,
    'schwierig': 3,
    'schwimmen': 2,
    'See': 2,
    'sehen': 1,
    'Sehens-': 3,
    'sehr': 1,
    'Seife': 3,
    'sein': 1,
    'Service': 2,
    'setzen': 3,
    'sie': 1,
    'singen': 2,
    'Situation': 3,
    'sitzen': 1,
    'Ski': 2,
    'so': 1,
    'Sofa': 2,
    'sofort': 2,
    'sogar': 3,
    'sollen': 2,
    'Sonne': 1,
    'spannend': 3,
    'sparen': 3,
    'Spaß': 2,
    'Spazier-': 3,
    'speichern': 3,
    'Speisekarte': 3,
    'Spiel': 1,
    'spielen': 1,
    'Sprache': 1,
    'sprechen': 1,
    'Sprech-': 3,
    'Stadt': 1,
    'stattfinden': 3,
    'stehen': 1,
    'Stelle': 3,
    'stellen': 2,
    'sterben': 3,
    'Stiefel': 3,
    'Stipen-': 3,
    'Stock': 3,
    'Strand': 1,
    'Straße': 1,
    'streiten': 3,
    'Student': 2,
    'studieren': 2,
    'Studium': 3,
    'super': 1,
    'Supermarkt': 2,
    'Suppe': 1,
    'süß': 1,
    'Süßigkeiten': 3,
    'sympathisch': 2,

    # ---- ALPHABETICAL SECTION T ----
    'Tablet': 3,
    'Tablette': 3,
    'tanzen': 2,
    'Tasche': 1,
    'Taschengeld': 3,
    'Tasse': 1,
    'Taxi': 1,
    'Tee': 1,
    'teilnehmen': 3,
    'Telefon': 1,
    'Teller': 1,
    'Tennis': 1,
    'Tipp': 3,
    'Torte': 3,
    'Tourist': 1,
    'tragen': 1,
    'trainieren': 3,
    'Training': 3,
    'Traum': 1,
    'Treppe': 2,
    'trinken': 1,
    'trocken': 2,
    'tun': 1,
    'Tür': 1,

    # ---- ALPHABETICAL SECTION Ü/U ----
    'über': 1,
    'übermorgen': 3,
    'übernachten': 3,
    'übersetzen': 3,
    'Über-': 3,
    'überweisen': 3,
    'üben': 2,
    'Uhr': 1,
    'um': 1,
    'umsteigen': 3,
    'umziehen': 3,
    'Umzug': 3,
    'unbedingt': 3,
    'und': 1,
    'Unfall': 3,
    'Universität': 3,
    'Unterkunft': 3,
    'unternehmen': 3,
    'Unterricht': 3,
    'unterschreiben': 3,
    'Unterschrift': 3,
    'Urlaub': 2,

    # ---- ALPHABETICAL SECTION V ----
    'Veranstal-': 3,
    'verbieten': 3,
    'verboten': 3,
    'verdienen': 3,
    'Verein': 3,
    'vereinbaren': 3,
    'vergessen': 3,
    'verkaufen': 2,
    'Verkehr': 3,
    'verletzen': 3,
    'verlieben': 3,
    'verlieren': 3,
    'vermieten': 3,
    'Vermieter': 3,
    'Vermieterin': 3,
    'verpassen': 3,
    'verreisen': 3,
    'verschieben': 3,
    'verschieden': 3,
    'Verspätung': 3,
    'versuchen': 2,
    'Vertrag': 3,
    'vielleicht': 1,
    'Vogel': 2,
    'voll': 2,
    'Volleyball': 3,
    'von': 1,
    'vor': 1,
    'vorbei': 2,
    'vorbereiten': 3,
    'vorgestern': 3,
    'vorsichtig': 2,
    'vorstellen': 3,
    'vorwärts': 3,

    # ---- ALPHABETICAL SECTION W ----
    'wach': 2,
    'Wagen': 2,
    'wählen': 2,
    'wahr': 2,
    'Wald': 1,
    'wandern': 3,
    'wann': 1,
    'warm': 1,
    'warten': 1,
    'Wäsche': 3,
    'waschen': 2,
    'Wasser': 1,
    'Webseite': 3,
    'wecken': 2,
    'weg': 2,
    'Weg': 2,
    'wegen': 2,
    'weiblich': 3,
    'weich': 2,
    'Wein': 1,
    'weinen': 2,
    'weit': 2,
    'weiter': 2,
    'Welt': 1,
    'wenigstens': 3,
    'werden': 2,
    'Werkstatt': 3,
    'Wettbewerb': 3,
    'wie': 1,
    'wieder': 1,
    'wiederholen': 3,
    'Wiederhören': 3,
    'Wiedersehen': 3,
    'wirklich': 1,
    'wissen': 2,
    'Witz': 2,
    'wo': 1,
    'woher': 2,
    'wohin': 2,
    'wohnen': 1,
    'Wohnung': 1,
    'Wohnzimmer': 3,
    'Wolke': 2,
    'wollen': 1,
    'Workshop': 3,
    'Wort': 1,
    'wunderbar': 2,
    'Wunsch': 2,
    'wünschen': 2,

    # ---- ALPHABETICAL SECTION Z ----
    'Zahl': 2,
    'Zahn': 2,
    'zeigen': 2,
    'Zeit': 1,
    'Zelt': 2,
    'Zettel': 2,
    'Zeugnis': 3,
    'Ziel': 2,
    'Zimmer': 1,
    'Zirkus': 2,
    'Zoo': 1,
    'Zucker': 2,
    'zufrieden': 2,
    'Zug': 1,
    'zuletzt': 3,
    'zumachen': 3,
    'zusammen': 2,
    'zwischen': 2,

    # ---- MISC / CATCH-ALL ----
    'am': 1,
    'ein': 1,
    'Glück-': 2,
}


def get_difficulty(word, word_type):
    w = word.strip()
    if w in OVERRIDES:
        return OVERRIDES[w]
    # Fallback: length heuristic
    wl = len(w)
    if wl <= 4:
        return 1
    elif wl <= 7:
        return 2
    else:
        return 3


def main():
    input_file = '/home/user/deutsch-lernen/word_data/quiz_csv/a2.csv'
    rows = []
    with open(input_file, 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        header = next(reader)
        # Strip existing difficulty column if present
        if header and header[-1] == 'difficulty':
            header = header[:-1]
        header.append('difficulty')
        rows.append(header)
        for row in reader:
            # Strip existing difficulty value if present
            if len(row) == len(header):
                row = row[:-1]
            word = row[5] if len(row) > 5 else ''
            word_type = row[8] if len(row) > 8 else ''
            difficulty = get_difficulty(word, word_type)
            row.append(str(difficulty))
            rows.append(row)

    with open(input_file, 'w', encoding='utf-8', newline='') as f:
        csv.writer(f).writerows(rows)

    # Print distribution
    counts = {1: 0, 2: 0, 3: 0}
    for row in rows[1:]:
        d = int(row[-1])
        counts[d] = counts.get(d, 0) + 1
    total = sum(counts.values())
    print(f"Total: {total}")
    for d in [1, 2, 3]:
        pct = counts[d] / total * 100
        print(f"  Difficulty {d}: {counts[d]} ({pct:.1f}%)")


if __name__ == '__main__':
    main()
