#!/usr/bin/env python3
"""
Rebalance 'Grammar & Core Verbs' by reassigning thematic words to existing categories.
Renames remaining entries to 'Grammar & Function Words'.
Uses batch processing with progress tracking.
"""

import csv
import json
import os
import re

CSV_PATH = "word_data/categorized_words.csv"
PROGRESS_PATH = "rebalance_progress.json"
SOURCE_CATEGORY = "Grammar & Core Verbs"
TARGET_GRAMMAR = "Grammar & Function Words"
BATCH_SIZE = 300

APPROVED_CATEGORIES = {
    "Numbers & Quantities",
    "Time & Calendar",
    "Family & Relationships",
    "Body & Health",
    "Food & Drink",
    "Home & Living",
    "Clothing & Appearance",
    "Work & Careers",
    "Education & Learning",
    "Travel & Tourism",
    "Transportation",
    "Shopping & Finance",
    "Language, Communication & Media",
    "Nature, Weather & Animals",
    "Sports & Leisure",
    "Arts & Culture",
    "Technology & Devices",
    "Society, Law & Politics",
    "Emotions & Personal Traits",
    "Places & Geography",
    "Grammar & Function Words",
}

# ──────────────────────────────────────────────────────────────────────────────
# Explicit word → category mapping (lowercase keys)
# ──────────────────────────────────────────────────────────────────────────────
WORD_MAP = {
    # ── Food & Drink ──────────────────────────────────────────────────────────
    "kochen": "Food & Drink",
    "backen": "Food & Drink",
    "braten": "Food & Drink",
    "grillen": "Food & Drink",
    "essen": "Food & Drink",
    "trinken": "Food & Drink",
    "schmecken": "Food & Drink",
    "servieren": "Food & Drink",
    "serviert": "Food & Drink",
    "würzen": "Food & Drink",
    "probieren": "Food & Drink",
    "cafeteria": "Food & Drink",
    "grill": "Food & Drink",
    "kneipe": "Food & Drink",
    "lokal": "Food & Drink",
    "restaurant": "Food & Drink",
    "brot": "Food & Drink",
    "milch": "Food & Drink",
    "wein": "Food & Drink",
    "bier": "Food & Drink",
    "kaffee": "Food & Drink",
    "tee": "Food & Drink",
    "saft": "Food & Drink",
    "fleisch": "Food & Drink",
    "gemüse": "Food & Drink",
    "obst": "Food & Drink",
    "käse": "Food & Drink",
    "suppe": "Food & Drink",
    "salat": "Food & Drink",
    "kuchen": "Food & Drink",
    "eis": "Food & Drink",
    "schokolade": "Food & Drink",
    "pizza": "Food & Drink",
    "reis": "Food & Drink",
    "butter": "Food & Drink",
    "zucker": "Food & Drink",
    "salz": "Food & Drink",
    "hungrig": "Food & Drink",
    "hunger": "Food & Drink",
    "durst": "Food & Drink",
    "durstig": "Food & Drink",
    "mahlzeit": "Food & Drink",
    "frühstück": "Food & Drink",
    "mittagessen": "Food & Drink",
    "abendessen": "Food & Drink",
    "speise": "Food & Drink",
    "getränk": "Food & Drink",
    "rezept": "Food & Drink",
    "kochtopf": "Food & Drink",
    "bestellen": "Food & Drink",
    "bestellung": "Food & Drink",
    "trinkt": "Food & Drink",
    "kocht": "Food & Drink",
    "magen": "Body & Health",

    # ── Transportation ────────────────────────────────────────────────────────
    "fahren": "Transportation",
    "fliegen": "Transportation",
    "parken": "Transportation",
    "einsteigen": "Transportation",
    "aussteigen": "Transportation",
    "umsteigen": "Transportation",
    "abfahren": "Transportation",
    "ankommen": "Transportation",
    "überfahren": "Transportation",
    "weggefahren": "Transportation",
    "abbiegen": "Transportation",
    "bremsen": "Transportation",
    "beschleunigen": "Transportation",
    "tanken": "Transportation",
    "auto": "Transportation",
    "bus": "Transportation",
    "zug": "Transportation",
    "bahn": "Transportation",
    "flugzeug": "Transportation",
    "schiff": "Transportation",
    "fahrrad": "Transportation",
    "taxi": "Transportation",
    "u-bahn": "Transportation",
    "straßenbahn": "Transportation",
    "motorrad": "Transportation",
    "bahnhof": "Transportation",
    "flughafen": "Transportation",
    "bushaltestelle": "Transportation",
    "parkplatz": "Transportation",
    "strecke": "Transportation",
    "umweg": "Transportation",

    # ── Work & Careers ────────────────────────────────────────────────────────
    "arbeiten": "Work & Careers",
    "jobben": "Work & Careers",
    "verdienen": "Work & Careers",
    "verdient": "Work & Careers",
    "bewerben": "Work & Careers",
    "kündigen": "Work & Careers",
    "anstellen": "Work & Careers",
    "einstellen": "Work & Careers",
    "entlassen": "Work & Careers",
    "beschäftigen": "Work & Careers",
    "streiken": "Work & Careers",
    "produzieren": "Work & Careers",
    "organisieren": "Work & Careers",
    "verwalten": "Work & Careers",
    "leiten": "Work & Careers",
    "beruf": "Work & Careers",
    "büro": "Work & Careers",
    "chef": "Work & Careers",
    "kollege": "Work & Careers",
    "kollegin": "Work & Careers",
    "gehalt": "Work & Careers",
    "firma": "Work & Careers",
    "betrieb": "Work & Careers",
    "stelle": "Work & Careers",
    "job": "Work & Careers",
    "aufgabe": "Work & Careers",
    "sekretär": "Work & Careers",
    "sekretärin": "Work & Careers",
    "betreuer": "Work & Careers",
    "betreuerin": "Work & Careers",
    "betreuung": "Work & Careers",
    "entlassung": "Work & Careers",
    "dienst": "Work & Careers",
    "karriere": "Work & Careers",
    "arbeitgeber": "Work & Careers",
    "arbeitnehmer": "Work & Careers",
    "arbeitslos": "Work & Careers",
    "arbeitszeit": "Work & Careers",
    "arbeitsplatz": "Work & Careers",
    "besprechung": "Work & Careers",
    "sitzung": "Work & Careers",

    # ── Education & Learning ──────────────────────────────────────────────────
    "lernen": "Education & Learning",
    "studieren": "Education & Learning",
    "unterrichten": "Education & Learning",
    "lehren": "Education & Learning",
    "erklären": "Education & Learning",
    "vorlesen": "Education & Learning",
    "nachschlagen": "Education & Learning",
    "üben": "Education & Learning",
    "übe": "Education & Learning",
    "recherchieren": "Education & Learning",
    "recherche": "Education & Learning",
    "schule": "Education & Learning",
    "universität": "Education & Learning",
    "lehrer": "Education & Learning",
    "lehrerin": "Education & Learning",
    "student": "Education & Learning",
    "studentin": "Education & Learning",
    "schüler": "Education & Learning",
    "schülerin": "Education & Learning",
    "klasse": "Education & Learning",
    "unterricht": "Education & Learning",
    "hausaufgabe": "Education & Learning",
    "prüfung": "Education & Learning",
    "zeugnis": "Education & Learning",
    "note": "Education & Learning",
    "kurs": "Education & Learning",
    "seminar": "Education & Learning",
    "vorlesung": "Education & Learning",
    "bildung": "Education & Learning",
    "ausbildung": "Education & Learning",
    "erziehung": "Education & Learning",
    "wissen": "Education & Learning",
    "kenntnisse": "Education & Learning",
    "fach": "Education & Learning",
    "aufgabe": "Work & Careers",   # overridden above; keep work

    # ── Home & Living ─────────────────────────────────────────────────────────
    "wohnen": "Home & Living",
    "schlafen": "Home & Living",
    "putzen": "Home & Living",
    "waschen": "Home & Living",
    "aufräumen": "Home & Living",
    "umziehen": "Home & Living",
    "einrichten": "Home & Living",
    "mieten": "Home & Living",
    "vermieten": "Home & Living",
    "vermietet": "Home & Living",
    "reinigen": "Home & Living",
    "bügeln": "Home & Living",
    "kochen": "Food & Drink",   # cooking stays Food
    "haus": "Home & Living",
    "wohnung": "Home & Living",
    "wohne": "Home & Living",
    "zimmer": "Home & Living",
    "küche": "Home & Living",
    "bad": "Home & Living",
    "schlafzimmer": "Home & Living",
    "wohnzimmer": "Home & Living",
    "garten": "Home & Living",
    "keller": "Home & Living",
    "dach": "Home & Living",
    "tür": "Home & Living",
    "fenster": "Home & Living",
    "möbel": "Home & Living",
    "tisch": "Home & Living",
    "stuhl": "Home & Living",
    "bett": "Home & Living",
    "sofa": "Home & Living",
    "schrank": "Home & Living",
    "kissen": "Home & Living",
    "lampe": "Home & Living",
    "treppe": "Home & Living",
    "klingel": "Home & Living",
    "briefkasten": "Home & Living",
    "heizung": "Home & Living",
    "schloss": "Home & Living",
    "schlüssel": "Home & Living",
    "eingang": "Home & Living",
    "ausgang": "Home & Living",
    "heim": "Home & Living",
    "hütte": "Home & Living",
    "kabine": "Home & Living",
    "schmutz": "Home & Living",
    "dreck": "Home & Living",
    "staub": "Home & Living",
    "spülen": "Home & Living",
    "sauber": "Home & Living",
    "schmutzig": "Home & Living",

    # ── Body & Health ─────────────────────────────────────────────────────────
    "atmen": "Body & Health",
    "heilen": "Body & Health",
    "untersuchen": "Body & Health",
    "operieren": "Body & Health",
    "erkranken": "Body & Health",
    "erholen": "Body & Health",
    "erholung": "Body & Health",
    "schwitzen": "Body & Health",
    "weh tun": "Body & Health",
    "wehtun": "Body & Health",
    "schmerzen": "Body & Health",
    "schmerz": "Body & Health",
    "krank": "Body & Health",
    "gesund": "Body & Health",
    "arzt": "Body & Health",
    "ärztin": "Body & Health",
    "medizin": "Body & Health",
    "krankheit": "Body & Health",
    "körper": "Body & Health",
    "kopf": "Body & Health",
    "hand": "Body & Health",
    "fuß": "Body & Health",
    "bein": "Body & Health",
    "arm": "Body & Health",
    "herz": "Body & Health",
    "bauch": "Body & Health",
    "rücken": "Body & Health",
    "gesicht": "Body & Health",
    "auge": "Body & Health",
    "ohr": "Body & Health",
    "nase": "Body & Health",
    "mund": "Body & Health",
    "zahn": "Body & Health",
    "haar": "Body & Health",
    "hals": "Body & Health",
    "schulter": "Body & Health",
    "knie": "Body & Health",
    "finger": "Body & Health",
    "magen": "Body & Health",
    "lunge": "Body & Health",
    "blut": "Body & Health",
    "krankenhaus": "Body & Health",
    "apotheke": "Body & Health",
    "tablette": "Body & Health",
    "impfen": "Body & Health",
    "schwangerschaft": "Body & Health",
    "geburt": "Body & Health",
    "diät": "Body & Health",
    "schlaf": "Body & Health",

    # ── Clothing & Appearance ─────────────────────────────────────────────────
    "anziehen": "Clothing & Appearance",
    "ausziehen": "Clothing & Appearance",
    "anpassen": "Clothing & Appearance",
    "nähen": "Clothing & Appearance",
    "kleid": "Clothing & Appearance",
    "hose": "Clothing & Appearance",
    "hemd": "Clothing & Appearance",
    "bluse": "Clothing & Appearance",
    "rock": "Clothing & Appearance",
    "jacke": "Clothing & Appearance",
    "mantel": "Clothing & Appearance",
    "schuhe": "Clothing & Appearance",
    "socken": "Clothing & Appearance",
    "pullover": "Clothing & Appearance",
    "anzug": "Clothing & Appearance",
    "krawatte": "Clothing & Appearance",
    "mütze": "Clothing & Appearance",
    "handschuhe": "Clothing & Appearance",
    "schal": "Clothing & Appearance",
    "gürtel": "Clothing & Appearance",
    "schmuck": "Clothing & Appearance",
    "mode": "Clothing & Appearance",
    "uniform": "Clothing & Appearance",
    "tragen": "Clothing & Appearance",

    # ── Shopping & Finance ────────────────────────────────────────────────────
    "kaufen": "Shopping & Finance",
    "verkaufen": "Shopping & Finance",
    "zahlen": "Shopping & Finance",
    "bezahlen": "Shopping & Finance",
    "kosten": "Shopping & Finance",
    "sparen": "Shopping & Finance",
    "ausgeben": "Shopping & Finance",
    "leihen": "Shopping & Finance",
    "borgen": "Shopping & Finance",
    "investieren": "Shopping & Finance",
    "einkaufen": "Shopping & Finance",
    "bestellen": "Shopping & Finance",
    "geld": "Shopping & Finance",
    "preis": "Shopping & Finance",
    "kosten": "Shopping & Finance",
    "rechnung": "Shopping & Finance",
    "kasse": "Shopping & Finance",
    "markt": "Shopping & Finance",
    "laden": "Shopping & Finance",
    "geschäft": "Shopping & Finance",
    "einkauf": "Shopping & Finance",
    "angebot": "Shopping & Finance",
    "rabatt": "Shopping & Finance",
    "steuer": "Shopping & Finance",
    "bank": "Shopping & Finance",
    "konto": "Shopping & Finance",
    "kredit": "Shopping & Finance",
    "ec-karte": "Shopping & Finance",
    "garantie": "Shopping & Finance",
    "kiosk": "Shopping & Finance",
    "supermarkt": "Shopping & Finance",
    "budget": "Shopping & Finance",
    "schulden": "Shopping & Finance",
    "schuld": "Shopping & Finance",
    "ware": "Shopping & Finance",
    "produkt": "Shopping & Finance",
    "marke": "Shopping & Finance",

    # ── Travel & Tourism ──────────────────────────────────────────────────────
    "reisen": "Travel & Tourism",
    "besichtigen": "Travel & Tourism",
    "übernachten": "Travel & Tourism",
    "übernachtet": "Travel & Tourism",
    "buchen": "Travel & Tourism",
    "urlauben": "Travel & Tourism",
    "abreisen": "Travel & Tourism",
    "urlaub": "Travel & Tourism",
    "reise": "Travel & Tourism",
    "hotel": "Travel & Tourism",
    "koffer": "Travel & Tourism",
    "pass": "Travel & Tourism",
    "visum": "Travel & Tourism",
    "strand": "Travel & Tourism",
    "sehenswürdigkeit": "Travel & Tourism",
    "tourist": "Travel & Tourism",
    "doppelzimmer": "Travel & Tourism",
    "einzelzimmer": "Travel & Tourism",
    "empfang": "Travel & Tourism",
    "eintritt": "Travel & Tourism",
    "ausflug": "Travel & Tourism",
    "reiseführer": "Travel & Tourism",
    "reisepass": "Travel & Tourism",
    "gepäck": "Travel & Tourism",
    "unterkunft": "Travel & Tourism",
    "pension": "Travel & Tourism",
    "rezeption": "Travel & Tourism",
    "sightseeing": "Travel & Tourism",

    # ── Language, Communication & Media ──────────────────────────────────────
    "sprechen": "Language, Communication & Media",
    "reden": "Language, Communication & Media",
    "sagen": "Language, Communication & Media",
    "erzählen": "Language, Communication & Media",
    "fragen": "Language, Communication & Media",
    "antworten": "Language, Communication & Media",
    "hören": "Language, Communication & Media",
    "lesen": "Language, Communication & Media",
    "schreiben": "Language, Communication & Media",
    "kommunizieren": "Language, Communication & Media",
    "telefonieren": "Language, Communication & Media",
    "mailen": "Language, Communication & Media",
    "chatten": "Language, Communication & Media",
    "diskutieren": "Language, Communication & Media",
    "berichten": "Language, Communication & Media",
    "veröffentlichen": "Language, Communication & Media",
    "siezen": "Language, Communication & Media",
    "duzen": "Language, Communication & Media",
    "sprache": "Language, Communication & Media",
    "wort": "Language, Communication & Media",
    "satz": "Language, Communication & Media",
    "text": "Language, Communication & Media",
    "brief": "Language, Communication & Media",
    "zeitung": "Language, Communication & Media",
    "buch": "Language, Communication & Media",
    "zeitschrift": "Language, Communication & Media",
    "radio": "Language, Communication & Media",
    "fernsehen": "Language, Communication & Media",
    "telefon": "Language, Communication & Media",
    "gespräch": "Language, Communication & Media",
    "nachricht": "Language, Communication & Media",
    "antwort": "Language, Communication & Media",
    "stimme": "Language, Communication & Media",
    "aussage": "Language, Communication & Media",
    "mitteilung": "Language, Communication & Media",
    "bericht": "Language, Communication & Media",
    "information": "Language, Communication & Media",
    "rede": "Language, Communication & Media",
    "meinung": "Language, Communication & Media",
    "übersetzung": "Language, Communication & Media",
    "abonnement": "Language, Communication & Media",
    "briefträger": "Language, Communication & Media",
    "schrift": "Language, Communication & Media",
    "ausdruck": "Language, Communication & Media",
    "erklärung": "Language, Communication & Media",
    "beschreibung": "Language, Communication & Media",
    "anzeige": "Language, Communication & Media",
    "werbung": "Language, Communication & Media",
    "inhalt": "Language, Communication & Media",
    "darstellung": "Language, Communication & Media",
    "notiz": "Language, Communication & Media",

    # ── Nature, Weather & Animals ─────────────────────────────────────────────
    "pflanzen": "Nature, Weather & Animals",
    "wachsen": "Nature, Weather & Animals",
    "blühen": "Nature, Weather & Animals",
    "welken": "Nature, Weather & Animals",
    "regnen": "Nature, Weather & Animals",
    "schneien": "Nature, Weather & Animals",
    "fressen": "Nature, Weather & Animals",
    "regnet": "Nature, Weather & Animals",
    "tier": "Nature, Weather & Animals",
    "hund": "Nature, Weather & Animals",
    "katze": "Nature, Weather & Animals",
    "vogel": "Nature, Weather & Animals",
    "fisch": "Nature, Weather & Animals",
    "baum": "Nature, Weather & Animals",
    "blume": "Nature, Weather & Animals",
    "pflanze": "Nature, Weather & Animals",
    "gras": "Nature, Weather & Animals",
    "wald": "Nature, Weather & Animals",
    "berg": "Nature, Weather & Animals",
    "see": "Nature, Weather & Animals",
    "fluss": "Nature, Weather & Animals",
    "meer": "Nature, Weather & Animals",
    "regen": "Nature, Weather & Animals",
    "schnee": "Nature, Weather & Animals",
    "sonne": "Nature, Weather & Animals",
    "wind": "Nature, Weather & Animals",
    "wolke": "Nature, Weather & Animals",
    "gewitter": "Nature, Weather & Animals",
    "wetter": "Nature, Weather & Animals",
    "natur": "Nature, Weather & Animals",
    "erde": "Nature, Weather & Animals",
    "luft": "Nature, Weather & Animals",
    "himmel": "Nature, Weather & Animals",
    "mond": "Nature, Weather & Animals",
    "stern": "Nature, Weather & Animals",
    "rose": "Nature, Weather & Animals",
    "gold": "Nature, Weather & Animals",
    "feuer": "Nature, Weather & Animals",
    "gas": "Nature, Weather & Animals",
    "gift": "Nature, Weather & Animals",
    "umwelt": "Nature, Weather & Animals",
    "klima": "Nature, Weather & Animals",
    "landschaft": "Nature, Weather & Animals",
    "wiese": "Nature, Weather & Animals",
    "küste": "Nature, Weather & Animals",
    "insel": "Nature, Weather & Animals",
    "tal": "Nature, Weather & Animals",

    # ── Sports & Leisure ──────────────────────────────────────────────────────
    "spielen": "Sports & Leisure",
    "schwimmen": "Sports & Leisure",
    "laufen": "Sports & Leisure",
    "joggen": "Sports & Leisure",
    "radfahren": "Sports & Leisure",
    "klettern": "Sports & Leisure",
    "wandern": "Sports & Leisure",
    "trainieren": "Sports & Leisure",
    "gewinnen": "Sports & Leisure",
    "verlieren": "Sports & Leisure",
    "spazieren": "Sports & Leisure",
    "turnen": "Sports & Leisure",
    "entspannen": "Sports & Leisure",
    "sport": "Sports & Leisure",
    "ball": "Sports & Leisure",
    "fußball": "Sports & Leisure",
    "tennis": "Sports & Leisure",
    "basketball": "Sports & Leisure",
    "fitness": "Sports & Leisure",
    "spiel": "Sports & Leisure",
    "wettkampf": "Sports & Leisure",
    "mannschaft": "Sports & Leisure",
    "trainer": "Sports & Leisure",
    "stadion": "Sports & Leisure",
    "spaß": "Sports & Leisure",
    "freizeit": "Sports & Leisure",
    "hobby": "Sports & Leisure",
    "camping": "Sports & Leisure",
    "ausflug": "Travel & Tourism",   # overrides
    "gymnastik": "Sports & Leisure",
    "yoga": "Sports & Leisure",
    "meditation": "Sports & Leisure",

    # ── Arts & Culture ────────────────────────────────────────────────────────
    "malen": "Arts & Culture",
    "zeichnen": "Arts & Culture",
    "singen": "Arts & Culture",
    "tanzen": "Arts & Culture",
    "musizieren": "Arts & Culture",
    "aufführen": "Arts & Culture",
    "fotografieren": "Arts & Culture",
    "kunst": "Arts & Culture",
    "musik": "Arts & Culture",
    "theater": "Arts & Culture",
    "film": "Arts & Culture",
    "kino": "Arts & Culture",
    "konzert": "Arts & Culture",
    "ausstellung": "Arts & Culture",
    "museum": "Arts & Culture",
    "bild": "Arts & Culture",
    "gemälde": "Arts & Culture",
    "skulptur": "Arts & Culture",
    "lied": "Arts & Culture",
    "instrument": "Arts & Culture",
    "gitarre": "Arts & Culture",
    "klavier": "Arts & Culture",
    "tanz": "Arts & Culture",
    "foto": "Arts & Culture",
    "cd": "Arts & Culture",
    "kultur": "Arts & Culture",
    "studio": "Arts & Culture",
    "bühne": "Arts & Culture",
    "rolle": "Arts & Culture",
    "szene": "Arts & Culture",
    "literatur": "Arts & Culture",
    "gedicht": "Arts & Culture",
    "roman": "Arts & Culture",
    "autor": "Arts & Culture",
    "messe": "Arts & Culture",

    # ── Technology & Devices ──────────────────────────────────────────────────
    "klicken": "Technology & Devices",
    "anklicken": "Technology & Devices",
    "tippen": "Technology & Devices",
    "herunterladen": "Technology & Devices",
    "installieren": "Technology & Devices",
    "programmieren": "Technology & Devices",
    "anmelden": "Technology & Devices",
    "abmelden": "Technology & Devices",
    "aufladen": "Technology & Devices",
    "ausschalten": "Technology & Devices",
    "einschalten": "Technology & Devices",
    "aktualisieren": "Technology & Devices",
    "drucken": "Technology & Devices",
    "computer": "Technology & Devices",
    "laptop": "Technology & Devices",
    "handy": "Technology & Devices",
    "smartphone": "Technology & Devices",
    "internet": "Technology & Devices",
    "app": "Technology & Devices",
    "software": "Technology & Devices",
    "programm": "Technology & Devices",
    "daten": "Technology & Devices",
    "datei": "Technology & Devices",
    "e-mail": "Technology & Devices",
    "website": "Technology & Devices",
    "rechner": "Technology & Devices",
    "online": "Technology & Devices",
    "drucker": "Technology & Devices",
    "bildschirm": "Technology & Devices",
    "tastatur": "Technology & Devices",
    "maus": "Technology & Devices",
    "netzwerk": "Technology & Devices",
    "passwort": "Technology & Devices",
    "benutzername": "Technology & Devices",
    "akku": "Technology & Devices",
    "stecker": "Technology & Devices",
    "kabel": "Technology & Devices",
    "gerät": "Technology & Devices",
    "technik": "Technology & Devices",
    "maschine": "Technology & Devices",
    "bedienungsanleitung": "Technology & Devices",
    "gebrauchsanweisung": "Technology & Devices",
    "dokument": "Technology & Devices",
    "ordner": "Technology & Devices",

    # ── Society, Law & Politics ───────────────────────────────────────────────
    "wählen": "Society, Law & Politics",
    "regieren": "Society, Law & Politics",
    "demonstrieren": "Society, Law & Politics",
    "protestieren": "Society, Law & Politics",
    "verhaften": "Society, Law & Politics",
    "urteilen": "Society, Law & Politics",
    "bestrafen": "Society, Law & Politics",
    "bestimmen": "Society, Law & Politics",
    "verbieten": "Society, Law & Politics",
    "erlauben": "Society, Law & Politics",
    "gesetz": "Society, Law & Politics",
    "staat": "Society, Law & Politics",
    "regierung": "Society, Law & Politics",
    "partei": "Society, Law & Politics",
    "wahl": "Society, Law & Politics",
    "demokratie": "Society, Law & Politics",
    "recht": "Society, Law & Politics",
    "polizei": "Society, Law & Politics",
    "gericht": "Society, Law & Politics",
    "strafe": "Society, Law & Politics",
    "gesellschaft": "Society, Law & Politics",
    "politik": "Society, Law & Politics",
    "bürger": "Society, Law & Politics",
    "frieden": "Society, Law & Politics",
    "krieg": "Society, Law & Politics",
    "armee": "Society, Law & Politics",
    "feuerwehr": "Society, Law & Politics",
    "kandidat": "Society, Law & Politics",
    "kandidatin": "Society, Law & Politics",
    "gemeinschaft": "Society, Law & Politics",
    "vertrag": "Society, Law & Politics",
    "verfassung": "Society, Law & Politics",
    "minister": "Society, Law & Politics",
    "präsident": "Society, Law & Politics",
    "behörde": "Society, Law & Politics",
    "amt": "Society, Law & Politics",
    "bürgermeister": "Society, Law & Politics",
    "parlament": "Society, Law & Politics",
    "streit": "Society, Law & Politics",
    "konflikt": "Society, Law & Politics",
    "konkurrenz": "Society, Law & Politics",

    # ── Emotions & Personal Traits ────────────────────────────────────────────
    "fühlen": "Emotions & Personal Traits",
    "lieben": "Emotions & Personal Traits",
    "hassen": "Emotions & Personal Traits",
    "ärgern": "Emotions & Personal Traits",
    "trauern": "Emotions & Personal Traits",
    "lachen": "Emotions & Personal Traits",
    "weinen": "Emotions & Personal Traits",
    "wünschen": "Emotions & Personal Traits",
    "hoffen": "Emotions & Personal Traits",
    "zweifeln": "Emotions & Personal Traits",
    "vertrauen": "Emotions & Personal Traits",
    "freuen": "Emotions & Personal Traits",
    "erschrecken": "Emotions & Personal Traits",
    "schämen": "Emotions & Personal Traits",
    "ärgern": "Emotions & Personal Traits",
    "liebe": "Emotions & Personal Traits",
    "hass": "Emotions & Personal Traits",
    "freude": "Emotions & Personal Traits",
    "trauer": "Emotions & Personal Traits",
    "angst": "Emotions & Personal Traits",
    "wut": "Emotions & Personal Traits",
    "stolz": "Emotions & Personal Traits",
    "neid": "Emotions & Personal Traits",
    "scham": "Emotions & Personal Traits",
    "einsamkeit": "Emotions & Personal Traits",
    "glück": "Emotions & Personal Traits",
    "kuss": "Emotions & Personal Traits",
    "lust": "Emotions & Personal Traits",
    "ärger": "Emotions & Personal Traits",
    "freundschaft": "Emotions & Personal Traits",
    "vergnügt": "Emotions & Personal Traits",
    "böse": "Emotions & Personal Traits",
    "peinlich": "Emotions & Personal Traits",
    "traurig": "Emotions & Personal Traits",
    "froh": "Emotions & Personal Traits",
    "glücklich": "Emotions & Personal Traits",
    "nett": "Emotions & Personal Traits",
    "freundlich": "Emotions & Personal Traits",
    "höflich": "Emotions & Personal Traits",
    "mutig": "Emotions & Personal Traits",
    "ehrlich": "Emotions & Personal Traits",
    "verrückt": "Emotions & Personal Traits",
    "süchtig": "Emotions & Personal Traits",
    "nervös": "Emotions & Personal Traits",
    "ängstlich": "Emotions & Personal Traits",
    "enttäuscht": "Emotions & Personal Traits",
    "überrascht": "Emotions & Personal Traits",
    "erleichtert": "Emotions & Personal Traits",
    "eifersüchtig": "Emotions & Personal Traits",
    "einsam": "Emotions & Personal Traits",
    "zufrieden": "Emotions & Personal Traits",
    "unzufrieden": "Emotions & Personal Traits",
    "wütend": "Emotions & Personal Traits",
    "aufgeregt": "Emotions & Personal Traits",
    "deprimiert": "Emotions & Personal Traits",
    "charakter": "Emotions & Personal Traits",
    "persönlichkeit": "Emotions & Personal Traits",
    "eigenschaft": "Emotions & Personal Traits",
    "gefühl": "Emotions & Personal Traits",

    # ── Places & Geography ────────────────────────────────────────────────────
    "stadt": "Places & Geography",
    "land": "Places & Geography",
    "dorf": "Places & Geography",
    "region": "Places & Geography",
    "kontinent": "Places & Geography",
    "norden": "Places & Geography",
    "süden": "Places & Geography",
    "osten": "Places & Geography",
    "westen": "Places & Geography",
    "hauptstadt": "Places & Geography",
    "bundesland": "Places & Geography",
    "straße": "Places & Geography",
    "platz": "Places & Geography",
    "viertel": "Places & Geography",
    "nachbarschaft": "Places & Geography",
    "ort": "Places & Geography",
    "zentrum": "Places & Geography",
    "außerhalb": "Places & Geography",
    "innerhalb": "Places & Geography",
    "weltweit": "Places & Geography",
    "zentral": "Places & Geography",
    "regional": "Places & Geography",
    "international": "Places & Geography",
    "lokal": "Food & Drink",  # override: lokal = pub/restaurant

    # ── Family & Relationships ────────────────────────────────────────────────
    "heiraten": "Family & Relationships",
    "scheiden": "Family & Relationships",
    "verloben": "Family & Relationships",
    "verabreden": "Family & Relationships",
    "verabredet": "Family & Relationships",
    "verabschieden": "Family & Relationships",
    "vorstellen": "Family & Relationships",
    "kennenlernen": "Family & Relationships",
    "familie": "Family & Relationships",
    "mutter": "Family & Relationships",
    "vater": "Family & Relationships",
    "kind": "Family & Relationships",
    "sohn": "Family & Relationships",
    "tochter": "Family & Relationships",
    "bruder": "Family & Relationships",
    "schwester": "Family & Relationships",
    "opa": "Family & Relationships",
    "oma": "Family & Relationships",
    "onkel": "Family & Relationships",
    "tante": "Family & Relationships",
    "cousin": "Family & Relationships",
    "nichte": "Family & Relationships",
    "neffe": "Family & Relationships",
    "freund": "Family & Relationships",
    "freundin": "Family & Relationships",
    "partner": "Family & Relationships",
    "ehemann": "Family & Relationships",
    "ehefrau": "Family & Relationships",
    "nachbar": "Family & Relationships",
    "nachbarin": "Family & Relationships",
    "ehe": "Family & Relationships",
    "beziehung": "Family & Relationships",
    "bekannt": "Family & Relationships",
    "frau": "Family & Relationships",
    "mann": "Family & Relationships",
    "schwester": "Family & Relationships",

    # ── Numbers & Quantities ──────────────────────────────────────────────────
    "zählen": "Numbers & Quantities",
    "messen": "Numbers & Quantities",
    "rechnen": "Numbers & Quantities",
    "wiegen": "Numbers & Quantities",
    "berechnen": "Numbers & Quantities",
    "zahl": "Numbers & Quantities",
    "menge": "Numbers & Quantities",
    "anzahl": "Numbers & Quantities",
    "mal": "Numbers & Quantities",
    "mal": "Numbers & Quantities",

    # ── Time & Calendar ───────────────────────────────────────────────────────
    "planen": "Time & Calendar",
    "terminieren": "Time & Calendar",
    "warten": "Time & Calendar",
    "dauern": "Time & Calendar",
    "passieren": "Time & Calendar",
    "stattfinden": "Time & Calendar",
    "enden": "Time & Calendar",
    "beginnen": "Time & Calendar",
    "anfangen": "Time & Calendar",
    "aufhören": "Time & Calendar",
    "saison": "Time & Calendar",
    "pause": "Time & Calendar",
    "termin": "Time & Calendar",
    "datum": "Time & Calendar",
    "zeitraum": "Time & Calendar",
    "zeitpunkt": "Time & Calendar",
    "frist": "Time & Calendar",
}

# ──────────────────────────────────────────────────────────────────────────────
# Compound-word component patterns → category
# If a word CONTAINS any of these substrings (case-insensitive), assign category
# Order matters: more specific patterns first
# ──────────────────────────────────────────────────────────────────────────────
COMPOUND_PATTERNS = [
    # Transportation
    ("fahrrad", "Transportation"),
    ("bahnhof", "Transportation"),
    ("flughafen", "Transportation"),
    ("parkplatz", "Transportation"),
    ("busfahrt", "Transportation"),
    ("zugfahrt", "Transportation"),
    ("fahrkarte", "Transportation"),

    # Food & Drink
    ("cafeteria", "Food & Drink"),
    ("restaurant", "Food & Drink"),
    ("küche", "Food & Drink"),
    ("bäckerei", "Food & Drink"),

    # Home & Living
    ("wohnzimmer", "Home & Living"),
    ("schlafzimmer", "Home & Living"),
    ("badezimmer", "Home & Living"),
    ("kinderzimmer", "Home & Living"),

    # Body & Health
    ("krankenhaus", "Body & Health"),
    ("arztpraxis", "Body & Health"),
    ("schwangerschaft", "Body & Health"),
    ("erkältung", "Body & Health"),

    # Technology & Devices
    ("computer", "Technology & Devices"),
    ("smartphone", "Technology & Devices"),
    ("internet", "Technology & Devices"),
    ("bedienungsanleitung", "Technology & Devices"),
    ("gebrauchsanweisung", "Technology & Devices"),

    # Work & Careers
    ("arbeitsplatz", "Work & Careers"),
    ("arbeitslos", "Work & Careers"),
    ("büroarbeit", "Work & Careers"),
    ("berufsschule", "Work & Careers"),

    # Education & Learning
    ("grundschule", "Education & Learning"),
    ("hochschule", "Education & Learning"),
    ("hausaufgabe", "Education & Learning"),
    ("lehrplan", "Education & Learning"),

    # Travel & Tourism
    ("doppelzimmer", "Travel & Tourism"),
    ("einzelzimmer", "Travel & Tourism"),
    ("übernacht", "Travel & Tourism"),

    # Shopping & Finance
    ("einkauf", "Shopping & Finance"),
    ("supermarkt", "Shopping & Finance"),
    ("bankkonto", "Shopping & Finance"),

    # Nature, Weather & Animals
    ("feuerwehr", "Society, Law & Politics"),  # fire brigade = society
    ("feuerzeug", "Home & Living"),            # lighter = home
    ("notausgang", "Home & Living"),           # emergency exit = home
    ("notfall", "Body & Health"),

    # Society
    ("polizei", "Society, Law & Politics"),
    ("rathaus", "Society, Law & Politics"),
    ("krankenvers", "Society, Law & Politics"),
]


def classify_word(word: str) -> str | None:
    """
    Returns a new category if the word should be reassigned,
    or None if it should stay as Grammar & Function Words.
    """
    w = word.strip().lower()

    # Direct lookup
    if w in WORD_MAP:
        cat = WORD_MAP[w]
        return cat if cat != SOURCE_CATEGORY else TARGET_GRAMMAR

    # Compound pattern matching
    for pattern, cat in COMPOUND_PATTERNS:
        if pattern in w:
            return cat

    return None   # keep as Grammar & Function Words


def load_progress():
    if os.path.exists(PROGRESS_PATH):
        with open(PROGRESS_PATH) as f:
            return json.load(f)
    return None

def save_progress(progress):
    with open(PROGRESS_PATH, "w") as f:
        json.dump(progress, f, indent=2)

def load_csv():
    rows = []
    with open(CSV_PATH, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows

def save_csv(rows):
    with open(CSV_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["id", "word", "difficulty", "level", "theme"])
        writer.writeheader()
        writer.writerows(rows)


def main():
    rows = load_csv()
    total_rows = len(rows)

    progress = load_progress()
    if progress is None or progress.get("status") == "done":
        progress = {
            "total_rows": total_rows,
            "processed_rows": 0,
            "last_processed_id": 0,
            "batch_size": BATCH_SIZE,
            "status": "running",
            "reassigned": 0,
        }
        save_progress(progress)
        print(f"Starting fresh. Total rows: {total_rows}")
    else:
        print(f"Resuming from row {progress['processed_rows']} / {total_rows}")

    start_idx = progress["processed_rows"]
    total_reassigned = progress.get("reassigned", 0)

    i = start_idx
    while i < total_rows:
        batch_end = min(i + BATCH_SIZE, total_rows)
        batch_reassigned = 0

        for j in range(i, batch_end):
            row = rows[j]
            if row["theme"] == SOURCE_CATEGORY:
                new_cat = classify_word(row["word"])
                if new_cat and new_cat != TARGET_GRAMMAR:
                    rows[j]["theme"] = new_cat
                    batch_reassigned += 1
                else:
                    rows[j]["theme"] = TARGET_GRAMMAR
            # Non-grammar rows: leave untouched (already correct category)

        total_reassigned += batch_reassigned
        progress["processed_rows"] = batch_end
        progress["last_processed_id"] = batch_end
        progress["reassigned"] = total_reassigned
        save_progress(progress)
        save_csv(rows)

        print(f"Batch {i+1}-{batch_end}: reassigned {batch_reassigned} words  |  total reassigned: {total_reassigned}")
        i = batch_end

    progress["status"] = "done"
    save_progress(progress)
    print(f"\nAll done! Total reassigned: {total_reassigned}")


if __name__ == "__main__":
    main()
