import csv

CSV_PATH = '/Users/mehrashojjat/Desktop/Works/MI/DL/word_data/quiz_csv/b1.csv'

# Batch 2: rows id 151–550
# Proper B1-level German example sentences reflecting each word's meaning
examples = {
    "151": "Biegen Sie an der nächsten Kreuzung links ab.",
    "152": "Sieh dir die Abbildung auf Seite fünf an und beschreibe sie.",
    "153": "Die Wanderung durch die Wildnis war ein großes Abenteuer.",
    "154": "Ich wollte kommen, aber ich hatte leider keine Zeit.",
    "155": "Der letzte Zug nach Berlin fährt um 22 Uhr ab.",
    "156": "Die Abfahrt des Zuges ist auf Gleis drei um 14 Uhr.",
    "157": "Bitte werfen Sie Ihren Abfall in den dafür vorgesehenen Behälter.",
    "158": "Der Abfalleimer in der Küche war schon wieder voll.",
    "159": "Der Preis hängt von der Qualität des Produktes ab.",
    "160": "Er ist stark abhängig von Kaffee und trinkt es morgens zuerst.",
    "161": "Ich muss noch Geld abheben, bevor die Bank schließt.",
    "162": "Meine Mutter hat mich heute vom Flughafen abgeholt.",
    "163": "Die Lehrerin hat die Hausaufgaben eingesammelt und korrigiert.",
    "164": "Ich habe meine Aufgaben gemacht und kann jetzt ausruhen.",
    "165": "Sein Antrag auf Urlaub wurde vom Chef abgelehnt.",
    "166": "Bei dem Fest gab es viele kalte und warme Getränke.",
    "167": "Er hat durch regelmäßiges Joggen drei Kilo abgenommen.",
    "168": "Ich bin früh aufgestanden, weil ich einen frühen Zug hatte.",
    "169": "Es ist sehr wichtig, pünktlich zu Terminen zu erscheinen.",
    "170": "Die Lehrerin war abwesend und eine Vertretung hat unterrichtet.",
    "171": "Denk daran, die Tür abzuschließen, wenn du das Haus verlässt.",
    "172": "Dieses Gerät kann man sowohl zu Hause als auch im Büro nutzen.",
    "173": "Er erzählt immer teure Geschichten, aber nicht alle sind wahr.",
    "174": "Ich bin ganz sicher, dass er pünktlich kommt.",
    "175": "Es war kalt draußen, trotzdem sind wir spazieren gegangen.",
    "176": "Wir sind heute Morgen früh aufgestanden.",
    "177": "Wir gehen jeden Freitagabend zusammen ins Kino.",
    "178": "Leider konnte ich an der Besprechung nicht teilnehmen.",
    "179": "Ich warte hier, bis er von der Arbeit zurückkommt.",
    "180": "Ich fahre heute zum Arzt.",
    "181": "Die alten Autos haben früher den Fluss stark verschmutzt.",
    "182": "Raucher sind oft stark abhängig vom Nikotin.",
    "183": "Ich fahre heute mit meinem Fahrrad zur Arbeit.",
    "184": "Er wurde pünktlich von der Schule abgeholt.",
    "185": "Kinder lernen in der Schule das Alphabet.",
    "186": "Er ist kleiner als sein Bruder.",
    "187": "Als er jung war, wohnte er in München.",
    "188": "Also, fangen wir jetzt mit dem Unterricht an.",
    "189": "Die alte Kirche in der Stadtmitte ist sehr schön.",
    "190": "In welchem Alter darf man in Deutschland Auto fahren?",
    "191": "Meine Großmutter lebt seit drei Jahren im Altenheim.",
    "192": "Das neue Altersheim bietet den Bewohnern viele Aktivitäten an.",
    "193": "Es gibt immer eine alternative Möglichkeit, das Problem zu lösen.",
    "194": "Wenn der Bus nicht fährt, gibt es zum Glück eine Alternative.",
    "195": "Die Ampel war rot, also bin ich stehen geblieben.",
    "196": "Er steht jeden Morgen früh an der Haltestelle.",
    "197": "Sie hat den Text genau analysiert und wichtige Punkte gefunden.",
    "198": "Das Restaurant bietet jeden Tag frische Gerichte an.",
    "199": "Bitte schreiben Sie Ihre Adresse und Telefonnummer auf das Formular.",
    "200": "Die zwei Bücher sind sich sehr ähnlich – sie haben fast dasselbe Thema.",
    "201": "Ich habe keine Ahnung, wo ich mein Portemonnaie hingelegt habe.",
    "202": "Der Supermarkt hat eine große Aktion – alle Produkte sind 20% günstiger.",
    "203": "Sport und andere Aktivitäten sind gut für die Gesundheit.",
    "204": "Was sind die aktuellen Nachrichten aus der Politik?",
    "205": "Er konnte die Entschuldigung seines Freundes gut akzeptieren.",
    "206": "Der Alarm hat uns mitten in der Nacht geweckt.",
    "207": "Zu viel Alkohol ist schädlich für die Gesundheit.",
    "208": "Alle Schüler müssen morgen die Hausaufgaben mitbringen.",
    "209": "Sie lebt allein in einer kleinen Wohnung in der Innenstadt.",
    "210": "Das war das allerbeste Konzert, das ich je gesehen habe.",
    "211": "Das Wetter war gut, allerdings war es etwas windig.",
    "212": "Allgemein gesagt ist das Niveau der Schüler sehr gut.",
    "213": "Der Alltag als Elternteil kann manchmal sehr stressig sein.",
    "214": "Der Film war wirklich langweilig – ich bin fast eingeschlafen.",
    "215": "Das ist eine alltägliche Situation, die fast jeder kennt.",
    "216": "Sie arbeitet in einem Büro in der Innenstadt.",
    "217": "Er hat schon alle Aufgaben erledigt.",
    "218": "Ich spreche Deutsch und auch ein bisschen Englisch.",
    "219": "Kannst du mir bitte beim Umzug helfen?",
    "220": "Wir treffen uns im Café an der Ecke.",
    "221": "Das war eine gute Idee – gut gemacht!",
    "222": "Das ist dem Mann, dem ich gestern begegnet bin.",
    "223": "Die Kinder waren sehr amüsiert von dem lustigen Clown.",
    "224": "Er kauft Brot und Milch im Supermarkt.",
    "225": "Es ist nicht leicht, Kritik zu akzeptieren.",
    "226": "Ich verstehe das nicht – das ist mir nicht klar.",
    "227": "Du musst das Badezimmer gründlich reinigen.",
    "228": "Ich schaffe das alleine, keine Sorge.",
    "229": "Hast du schon gegessen? – Ja, ich habe schon gegessen.",
    "230": "Hast du den neuen Film schon gesehen?",
    "231": "Das war günstig, allerdings war die Qualität nicht so gut.",
    "232": "Er wohnt hier in der Nähe des Bahnhofs.",
    "233": "Heute Abend koche ich Spaghetti für die ganze Familie.",
    "234": "Das Kind war ängstlich und wollte nicht alleine schlafen.",
    "235": "Sie hat heute ein Kleid und einen Mantel an.",
    "236": "Bitte klicke auf den Link und fülle das Formular aus.",
    "237": "Der Zug ist pünktlich um 10 Uhr auf dem Bahnhof angekommen.",
    "238": "Auf der Ankunftstafel steht, dass der Flug Verspätung hat.",
    "239": "Die Firma hat einen neuen Verkaufsstart für nächste Woche angekündigt.",
    "240": "Bitte schicken Sie die Dokumente als Anlage per E-Mail.",
    "241": "Die Anleitung für das Gerät ist leider sehr schwer zu verstehen.",
    "242": "Du kannst dich online für den Kurs anmelden.",
    "243": "Die Anmeldung für die Veranstaltung ist bis Freitag möglich.",
    "244": "Er konnte das Angebot leider nicht annehmen.",
    "245": "Ich habe eine Annonce in der Zeitung gefunden, die perfekt zu mir passt.",
    "246": 'In formellen Briefen beginnt die Anrede mit \u201eSehr geehrte Damen und Herren\u201c.',
    "247": "Ich habe gerade einen Anruf von meiner Mutter bekommen.",
    "248": "Bitte hinterlasse eine Nachricht auf dem Anrufbeantworter.",
    "249": "Am Flughafen gab es eine wichtige Ansage über die Sicherheitsregeln.",
    "250": "Das Geschäft hat ein tolles Angebot für das Wochenende.",
    "251": "Die Lehrerin hat uns einen anderen Text zum Lesen gegeben.",
    "252": "Einerseits ist das Angebot günstig, andererseits ist die Qualität schlecht.",
    "253": "Sie möchte ihren Alltag ändern und mehr Sport treiben.",
    "254": "Die Änderung des Stundenplans wurde kurzfristig bekannt gegeben.",
    "255": "Das hat er diesmal anders gemacht als beim letzten Mal.",
    "256": "Sein Abschluss wurde in Deutschland leider nicht anerkannt.",
    "257": "Wann fängst du mit dem neuen Job an?",
    "258": "Am Anfang war die Sprache sehr schwierig für mich.",
    "259": "Anfangs hatte sie Angst, aber dann hat sie sich schnell gewöhnt.",
    "260": "Auf dem Formular müssen Sie Ihren Namen und Ihre Adresse angeben.",
    "261": "Bitte überprüfen Sie alle Angaben auf dem Formular sorgfältig.",
    "262": "Nach dem Unfall wurden alle Angehörigen sofort informiert.",
    "263": "Das Wetter heute ist sehr angenehm – nicht zu heiß und nicht zu kalt.",
    "264": "Was ist gestern Abend auf der Party passiert?",
    "265": "Wie geht es dir? – Es geht mir gut, danke.",
    "266": "Es wird bald dunkel – wir sollten nach Hause gehen.",
    "267": "Mit dem neuen Zug kommen wir viel schneller ans Ziel.",
    "268": "Meine Schwester studiert in Wien.",
    "269": "Das Konzert wurde bereits für die nächste Woche angekündigt.",
    "270": "Was meinst du damit? Kannst du das genauer erklären?",
    "271": "Du musst unbedingt zum Arzt gehen – das klingt ernst.",
    "272": "In dieser Stadt sind die Wohnungen sehr teuer und schwer zu finden.",
    "273": "Bitte vergessen Sie nicht, das Formular bis Freitag abzugeben.",
    "274": "Wir suchen eine günstige Wohnung in der Nähe der Universität.",
    "275": "Er ist schon früh am Morgen zum Supermarkt gegangen.",
    "276": "Das Buch gehört dem Schüler in der ersten Reihe.",
    "277": "Einerseits ist es praktisch, andererseits kostet es viel.",
    "278": "Das Gesetz hat sich in diesem Jahr stark geändert.",
    "279": "Sein Diplom wurde nach vielen Monaten endlich anerkannt.",
    "280": "An dem Kurs haben viele Studenten aus verschiedenen Ländern teilgenommen.",
    "281": "Ich bin dagegen, dass wir das Projekt ohne Plan beginnen.",
    "282": "Das Konzert findet an diesem Wochenende statt.",
    "283": "Die Anwältin hat ihren Mandanten sehr gut vor Gericht vertreten.",
    "284": "Das Display zeigt die aktuelle Temperatur an.",
    "285": "Er hat eine Anzeige wegen Diebstahls bei der Polizei erstattet.",
    "286": "Das Plakat zieht viele Besucher an.",
    "287": "Er trägt zum Vorstellungsgespräch immer einen Anzug.",
    "288": "Bitte legen Sie das Telefon auf den Apparat und warten Sie.",
    "289": "Nach dem langen Spaziergang hatte ich großen Appetit.",
    "290": "Aprikosen sind im Sommer besonders süß und lecker.",
    "291": "Sie arbeitet seit fünf Jahren in einer Schule als Lehrerin.",
    "292": "Die Arbeit macht ihm viel Spaß, weil das Team sehr nett ist.",
    "293": "Der Arbeiter hat den ganzen Tag auf der Baustelle gearbeitet.",
    "294": "Die Arbeiterin hat ihre Schicht pünktlich begonnen.",
    "295": "Ohne Arbeitserlaubnis darf er in Deutschland nicht arbeiten.",
    "296": "Er ist seit sechs Monaten arbeitslos und sucht eine neue Stelle.",
    "297": "Die Arbeitslosigkeit ist in dieser Region leider sehr hoch.",
    "298": "Sie sucht einen modernen Arbeitsplatz mit guter Ausstattung.",
    "299": "Er hat eine neue Arbeitsstelle als Ingenieur gefunden.",
    "300": "Kannst du bitte den Drucker an den Computer anschließen?",
    "301": "Er hat den Anschluss an die neue Stelle problemlos geschafft.",
    "302": "Bitte schnallen Sie sich an – wir fahren gleich los.",
    "303": "Wir haben uns gemeinsam einen Film im Kino angesehen.",
    "304": "Darf ich Sie kurz ansprechen? Ich habe eine Frage.",
    "305": "Du hast keinen Anspruch auf eine Rückerstattung ohne Quittung.",
    "306": "Die Firma hat drei neue Mitarbeiter angestellt.",
    "307": "Der Angestellte arbeitet seit zehn Jahren in diesem Büro.",
    "308": "Die Angestellte hat alle Dokumente sorgfältig vorbereitet.",
    "309": "Die lange Reise war sehr anstrengend – wir sind alle erschöpft.",
    "310": "Er hat einen Antrag auf Kindergeld beim Amt gestellt.",
    "311": "Diese Regel wird in der Praxis selten angewendet.",
    "312": "Alle Teilnehmer müssen bei der Sitzung anwesend sein.",
    "313": "Bitte antworte auf die Frage in einem ganzen Satz.",
    "314": "Die Antwort auf die erste Frage war leider falsch.",
    "315": "In dieser Stadt sind die Wohnungen sehr begehrt.",
    "316": "Hast du schon eine Antwort auf deine Bewerbung bekommen?",
    "317": "Wenn du dich erkältest, solltest du viel Tee trinken.",
    "318": "Sie hat gestern ein neues Buch im Buchladen gekauft.",
    "319": "Wir haben eine kleine Wohnung in der Nähe des Zentrums gemietet.",
    "320": "Hast du einen Stift? Ich brauche einen zum Schreiben.",
    "321": "Bitte stell die Musik leiser – das Baby schläft.",
    "322": "Ich habe nichts falsch gemacht – das war ein Versehen.",
    "323": "Ich suche einen guten Mechaniker für mein Auto.",
    "324": "Er hat eine neue Arbeitsstelle in München gefunden.",
    "325": "Das Restaurant liegt direkt bei der Kirche.",
    "326": "Ich habe meinen verlorenen Schlüssel endlich gefunden.",
    "327": "Du musst zuerst das Kabel anschließen, bevor du es einschaltest.",
    "328": "Das Schild an der Wand zeigt den Weg zur Toilette.",
    "329": "Wir haben noch viel zu erledigen, bevor wir anfangen können.",
    "330": "Er hat das Radio leise angemacht.",
    "331": "Stell die Blumen bitte in eine Vase und stelle sie auf den Tisch.",
    "332": "Das Unternehmen möchte nächsten Monat neue Mitarbeiter anstellen.",
    "333": "Musst du morgen früh aufstehen?",
    "334": "Die Klausur war sehr anstrengend, aber ich glaube, ich habe sie bestanden.",
    "335": "Diese Methode kann man in vielen Situationen anwenden.",
    "336": "Beim Elternabend müssen alle Eltern anwesend sein.",
    "337": "Ich meine, wir sollten das Problem direkt ansprechen.",
    "338": "Wann bekommst du Bescheid, ob du den Job bekommst?",
    "339": "Ihr rotes Kleid ist ihr gestern sofort aufgefallen.",
    "340": "Der Lehrer hat die Klasse aufgefordert, ruhig zu sein.",
    "341": "Die Aufforderung zur Zahlung kam per Post an.",
    "342": "Das Theaterstück wurde sehr erfolgreich aufgeführt.",
    "343": "Die Aufgabe war schwieriger als erwartet, aber lösbar.",
    "344": "Er hat das Rennen nach einem Sturz aufgegeben.",
    "345": "Der Stau hat uns zwei Stunden aufgehalten.",
    "346": "Bitte heb den Beleg auf – du könntest ihn später brauchen.",
    "347": "Er hat mit dem Rauchen aufgehört und fühlt sich viel besser.",
    "348": "Vergiss nicht, dein Handy vor dem Schlafen aufzuladen.",
    "349": "Der Verein wurde nach dem Skandal aufgelöst.",
    "350": "Die Schüler haben aufmerksam zugehört, als die Lehrerin erklärte.",
    "351": "Das Interview wurde live im Radio aufgenommen.",
    "352": "Die Aufnahme des Konzerts ist von sehr guter Qualität.",
    "353": "Er ärgert sich darüber, dass der Bus wieder Verspätung hat.",
    "354": "Sie hat viel Ärger mit ihrem Vermieter wegen der Heizung.",
    "355": "Es ist ärgerlich, wenn man am Morgen den Zug verpasst.",
    "356": "In dieser Stadt sind viele Familien arm und brauchen Hilfe.",
    "357": "Er hat sich den Arm bei einem Sportunfall gebrochen.",
    "358": "Es gibt verschiedene Arten, Deutsch zu lernen.",
    "359": "Der Artikel in der Zeitung handelt von einem neuen Forschungsprojekt.",
    "360": "Der Arzt hat mir geraten, mehr Wasser zu trinken.",
    "361": "Die Ärztin hat sich alle Symptome genau angehört.",
    "362": "Er hat in Deutschland Asyl beantragt.",
    "363": "Beim Sport ist es wichtig, tief und regelmäßig zu atmen.",
    "364": "Nach dem langen Laufen war er außer Atem.",
    "365": "Er spricht Englisch und auch ein wenig Französisch.",
    "366": "Das Buch liegt auf dem Tisch.",
    "367": "Wir haben einen angenehmen Abend mit Freunden verbracht.",
    "368": "Er war blass vor Schreck, als er die Nachricht hörte.",
    "369": "Das Essen war zu salzig und zu scharf.",
    "370": "Er hat die Hoffnung auf eine bessere Zukunft nicht aufgegeben.",
    "371": "Ich brauche eine Stunde, um zur Arbeit zu fahren.",
    "372": "Das Gebäude wurde im Jahr 1920 gebaut.",
    "373": "Ich bin sicher, dass er das gesagt hat.",
    "374": "Das Gespräch wurde auf Band aufgenommen.",
    "375": "Das Konzert wurde auf Video aufgenommen.",
    "376": "Ich lese immer Zeitung am Morgen.",
    "377": "Ich habe heute keine Zeit mehr.",
    "378": "Er hat das Buch in zwei Tagen gelesen.",
    "379": "Wir sind durch den Park spaziert.",
    "380": "Ich mag Sport, und ich spiele auch gerne Musik.",
    "381": "Hast du es schon gesehen? Es liegt auf dem Tisch.",
    "382": "Er ist ausgebildeter Koch und arbeitet in einem Fünf-Sterne-Hotel.",
    "383": "Kannst du das Dokument bitte ausdrucken und mir bringen?",
    "384": "Der Ausdruck 'unter Druck stehen' bedeutet, sehr beschäftigt zu sein.",
    "385": "Bitte machen Sie einen Ausdruck des Formulars und bringen ihn mit.",
    "386": "Die zwei Brüder leben jetzt auseinander – einer in Berlin, einer in Wien.",
    "387": "Die Ausfahrt zur Autobahn ist in zwei Kilometern.",
    "388": "Der Unterricht ist heute wegen Schnee ausgefallen.",
    "389": "Am Wochenende machen wir einen Ausflug in die Berge.",
    "390": "Bitte füllen Sie das Anmeldeformular vollständig aus.",
    "391": "Die neuste Ausgabe des Magazins ist gestern erschienen.",
    "392": "Der Ausgang des Museums ist auf der rechten Seite.",
    "393": "Er gibt zu viel Geld für Kleidung aus.",
    "394": "Gehst du heute Abend aus? – Ja, wir gehen in eine Bar.",
    "395": "Das Restaurant war ausgezeichnet – das Essen war fantastisch.",
    "396": "Als Aushilfe in der Sporthalle arbeite ich nur am Wochenende.",
    "397": "Sie hat zwei Jahre im Ausland gelebt und viele Sprachen gelernt.",
    "398": "Wir müssen das Zimmer aufräumen, bevor die Gäste kommen.",
    "399": "Reg dich nicht so auf – das ist doch kein Problem.",
    "400": "Er steht jeden Morgen um sechs Uhr auf.",
    "401": "Die Firma hat mir einen neuen Auftrag gegeben.",
    "402": "Die Sängerin tritt heute Abend auf einer großen Bühne auf.",
    "403": "Ihr erster Auftritt auf der Bühne war sehr beeindruckend.",
    "404": "Er wacht jeden Morgen um sieben Uhr auf.",
    "405": "Die Konjunktur entwickelt sich wieder aufwärts.",
    "406": "Der Aufzug ist außer Betrieb – wir müssen die Treppe nehmen.",
    "407": "Sie hat braune Augen und lange Haare.",
    "408": "Warte kurz – ich komme in einem Augenblick.",
    "409": "Er kommt aus Deutschland und lebt jetzt in Österreich.",
    "410": "Er hat die Tür abgeschlossen und den Schlüssel mitgenommen.",
    "411": "Ist es sicher, nachts alleine durch dieses Viertel zu gehen?",
    "412": "Sie ist ausgebildete Krankenschwester und arbeitet im Krankenhaus.",
    "413": "Kannst du das Dokument bitte ausdrucken?",
    "414": "Das Buch gehört zum Pflichtprogramm dieses Kurses.",
    "415": "Das Paket kommt von einer Freundin aus der Schweiz.",
    "416": "Er versteht das Problem nicht.",
    "417": "Er hat das Wochenende mit Freunden in Hamburg verbracht.",
    "418": "Dieses Geschenk ist für meine Mutter zum Geburtstag.",
    "419": "Das ist ein schönes Land mit viel Geschichte.",
    "420": "Hast du aufgepasst? Die Lehrerin hat eine wichtige Erklärung gegeben.",
    "421": "Das bringt mir sehr viel – danke für die Hilfe.",
    "422": "Das Buch liegt auf dem Regal.",
    "423": "Er hat schon das Frühstück vorbereitet.",
    "424": "Die Reise durch die Alpen war sehr aufregend.",
    "425": "Der Unterricht findet auf dem Schulgelände statt.",
    "426": "Wir können uns morgen treffen, wenn du kannst.",
    "427": "Er kauft Zeitung und Kaffee jeden Morgen.",
    "428": "An der Konferenz haben viele Experten aus aller Welt teilgenommen.",
    "429": "Er braucht eine Stunde für den Weg zur Arbeit.",
    "430": "Wir fahren mit dem Zug und kommen gegen Abend an.",
    "431": "Warte einen Augenblick – ich bin gleich fertig.",
    "432": "Es ist wichtig, deutsche Wörter richtig auszusprechen.",
    "433": "Ihre Aussprache ist sehr gut für jemanden, der erst sechs Monate Deutsch lernt.",
    "434": "Das Museum stellt Gemälde aus dem 19. Jahrhundert aus.",
    "435": "Die Ausstellung im Stadtmuseum zeigt alte Fotos der Stadt.",
    "436": "Du kannst aus drei verschiedenen Farben auswählen.",
    "437": "Im Supermarkt gibt es eine große Auswahl an frischem Obst.",
    "438": "Du brauchst einen gültigen Ausweis, um ein Konto zu eröffnen.",
    "439": "Sie ist letzten Monat aus ihrer alten Wohnung ausgezogen.",
    "440": "Er fährt jeden Tag mit dem Auto zur Arbeit.",
    "441": "Auf der Autobahn darf man in manchen Abschnitten so schnell fahren wie man möchte.",
    "442": "Der Automat gibt kein Wechselgeld zurück – bitte passend zahlen.",
    "443": "Das Licht geht automatisch aus, wenn niemand im Raum ist.",
    "444": "Der Autor dieses Romans ist sehr bekannt in Deutschland.",
    "445": "Die Autorin hat ihr neues Buch heute auf der Buchmesse vorgestellt.",
    "446": "Die Ausländerin arbeitet seit einem Jahr in Deutschland.",
    "447": "Er hat viele ausländische Freunde und spricht mehrere Sprachen.",
    "448": "Bitte mach das Licht aus und schließ die Fenster, bevor du gehst.",
    "449": "In diesem Fall machen wir eine Ausnahme – das passiert nicht nochmal.",
    "450": "Das Geld reicht nicht aus, um die Miete zu bezahlen.",
    "451": "Das Ergebnis ist ausreichend, aber er könnte besser werden.",
    "452": "Kannst du der Kollegin bitte ausrichten, dass das Meeting verschoben wurde?",
    "453": "Nach der langen Reise brauche ich dringend eine Pause, um mich auszuruhen.",
    "454": "Er wurde aus dem Wettbewerb ausgeschlossen, weil er gegen die Regeln verstoßen hat.",
    "455": "Diese Information ist ausschließlich für Mitglieder des Clubs.",
    "456": "Du siehst heute sehr müde aus – hast du schlecht geschlafen?",
    "457": "Das Haus sieht von außen sehr schön aus.",
    "458": "Das Büro befindet sich außerhalb der Stadt und ist nur mit dem Auto erreichbar.",
    "459": "Ich beurteile den Menschen nicht nach seinem äußerlichen Aussehen.",
    "460": "Alle außer ihm haben an dem Ausflug teilgenommen.",
    "461": "Er spricht Deutsch und außerdem noch zwei weitere Sprachen.",
    "462": "Das ist eine gute Möglichkeit, etwas Neues zu lernen.",
    "463": "Das Bild wurde in einer Galerie ausgestellt.",
    "464": "Sein Führerschein wurde ihm nach einem Unfall ausgestellt.",
    "465": "Wie lange dauert die Reise von Berlin nach München?",
    "466": "Ich sehe dich morgen – wir treffen uns vor dem Kino.",
    "467": "Er ist letzten Monat aus seiner alten Wohnung ausgezogen.",
    "468": "Das System startet automatisch neu, wenn ein Fehler auftritt.",
    "469": "Er hat zwei Sprachen gelernt und möchte noch eine weitere dazufügen.",
    "470": "Der Kellner hat uns verschiedene Getränke angeboten.",
    "471": "Möchtest du etwas trinken? – Ja, gerne einen Kaffee.",
    "472": "Ich war völlig erschöpft nach dem langen Arbeitstag.",
    "473": "Wenn du wieder in der Stadt bist, sollten wir uns treffen.",
    "474": "Das würde ich gerne noch einmal machen.",
    "475": "Ich habe den Film schon gesehen, aber er ist wirklich gut.",
    "476": "Das äußerliche Erscheinungsbild ist nicht das Wichtigste.",
    "477": "Das Museum ist heute geöffnet und der Eintritt kostet fünf Euro.",
    "478": "Ich bin zu beschäftigt – ich habe keine Zeit dafür.",
    "479": "Kann ich bar bezahlen oder nur mit Karte?",
    "480": "Ich habe leider kein Bargeld dabei – kann ich mit Karte zahlen?",
    "481": "Er hat sich einen Bart wachsen lassen und sieht jetzt ganz anders aus.",
    "482": "Sie spielt jeden Mittwoch Basketball mit ihrer Schulmannschaft.",
    "483": "Die Kinder haben im Kunstunterricht gebastelt und bunte Figuren gemacht.",
    "484": "Die Batterie des Handys ist leer und muss aufgeladen werden.",
    "485": "Er hat in drei Monaten ein kleines Holzhaus im Garten gebaut.",
    "486": "Der Bau des neuen Bahnhofs dauert noch zwei Jahre.",
    "487": "Die Baustelle hat den Verkehr stark verlangsamt.",
    "488": "Der Bauer arbeitet jeden Tag früh morgens auf dem Feld.",
    "489": "Im Herbst verlieren die Bäume im Park ihre Blätter.",
    "490": "Bitte beachten Sie die Hinweisschilder im Gebäude.",
    "491": "Der Beamte hat alle Dokumente geprüft und den Antrag bearbeitet.",
    "492": "Die Beamtin hat alle Fragen geduldig und freundlich beantwortet.",
    "493": "Er hat einen Antrag auf Wohngeld beim Amt beantragt.",
    "494": "Bitte beantworte alle Fragen vollständig und ehrlich.",
    "495": "Der Bedarf an Pflegepersonal ist in Deutschland sehr hoch.",
    "496": "Was bedeutet dieses Wort auf Deutsch?",
    "497": "Die Bedeutung dieses Satzes ist mir nicht ganz klar.",
    "498": "An Weihnachten backt sie immer Kekse für die ganze Familie.",
    "499": "Die Bäckerei um die Ecke hat frisches Brot und Brötchen.",
    "500": "Er geht am Wochenende gerne im See Baden.",
    "501": "Das Bad in diesem Hotel ist sehr sauber und modern.",
    "502": "Er liegt gerne in der Badewanne und liest ein Buch.",
    "503": "Wir fahren mit der Bahn nach Hamburg – das ist günstiger als das Flugzeug.",
    "504": "Die Straßenbahn hält direkt vor dem Rathaus.",
    "505": "Die U-Bahn fährt hier alle fünf Minuten.",
    "506": "Wir treffen uns am Bahnhof um halb acht.",
    "507": "Bitte gehen Sie auf Bahnsteig drei – Ihr Zug fährt gleich ab.",
    "508": "Auf dem Balkon meiner Wohnung wachsen Blumen und Kräuter.",
    "509": "Die Kinder spielen im Garten mit dem Ball.",
    "510": "Er hebt Geld von der Bank ab, um den Vermieter zu bezahlen.",
    "511": "Er sitzt auf der Bank im Park und liest die Zeitung.",
    "512": "Bitte geben Sie Ihre Bankleitzahl beim Überweisungsformular an.",
    "513": "Sein Visum wurde beantragt und wir warten auf eine Antwort.",
    "514": "Die E-Mail wurde innerhalb von 24 Stunden beantwortet.",
    "515": "Das Wort 'freundlich' endet mit dem Suffix -lich.",
    "516": "Heute ist das Wetter besonders schön.",
    "517": "Er hat sich beim Arzt vorgestellt.",
    "518": "Sie war nicht zu Hause, als ich anrief.",
    "519": "Es haben viele Personen an der Veranstaltung teilgenommen.",
    "520": "Ist es möglich, morgen früh einen Termin zu bekommen?",
    "521": "Sie tanzt seit ihrer Kindheit und nimmt jeden Samstag Unterricht.",
    "522": "Setzen Sie sich vorne, damit Sie die Tafel gut sehen können.",
    "523": "kannst du bitte für das Abendessen zahlen? Ich habe kein Bargeld.",
    "524": "Der Lärm von der Baustelle behindert uns beim Arbeiten.",
    "525": "Er muss viele Formulare bei der Behörde einreichen.",
    "526": "Beide Kinder gehen in dieselbe Schule.",
    "527": "Er hat sich das Bein beim Skifahren gebrochen.",
    "528": "Ich habe beinahe den letzten Bus verpasst.",
    "529": "Zum Beispiel kann man Deutsch durch Bücher und Filme lernen.",
    "530": "Der Hund hat ihn ins Bein gebissen.",
    "531": "Er zahlt monatlich einen Beitrag für den Sportverein.",
    "532": "Dieser Schauspieler ist in ganz Deutschland bekannt.",
    "533": "Ein Bekannter von mir hat mir eine gute Stelle empfohlen.",
    "534": "Eine Bekannte hat mir dieses Restaurant empfohlen.",
    "535": "Das ist das bekannteste Wahrzeichen der Stadt.",
    "536": "Ich bekomme jeden Monat mein Gehalt auf das Konto.",
    "537": "Die Bedienungsanleitung erklärt Schritt für Schritt, wie man das Gerät bedient.",
    "538": "Eine wichtige Bedingung für den Job ist, dass man Deutsch spricht.",
    "539": "Er hat die Aufgabe pünktlich beendet und das Ergebnis abgegeben.",
    "540": "Sie hat die Prüfung bestanden und fühlt sich befreit.",
    "541": "Die Leistung war befriedigend, aber noch nicht ausgezeichnet.",
    "542": "Ich habe ihn gestern zufällig auf der Straße begegnet.",
    "543": "Die Fans waren begeistert von dem Konzert.",
    "544": "Der Unterricht beginnt jeden Morgen pünktlich um acht Uhr.",
    "545": "Am Beginn des Kurses stellt sich jeder kurz vor.",
    "546": "Er begleitet seine Mutter jeden Samstag zum Markt.",
    "547": "Das Budget für das Projekt wurde auf 10.000 Euro begrenzt.",
    "548": "Bitte begründe deine Antwort mit einem oder zwei Sätzen.",
    "549": "Die Begründung für die Entscheidung war nicht überzeugend.",
    "550": "Der Gastgeber hat die Gäste herzlich begrüßt.",
}

with open(CSV_PATH, newline='', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    rows = list(reader)

updated = 0
for r in rows:
    if r['id'] in examples:
        r['example_de'] = examples[r['id']]
        updated += 1

with open(CSV_PATH, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

filled = sum(1 for r in rows if r['example_de'].strip())
print(f"Updated {updated} rows. Total filled: {filled} / {len(rows)}")
print("\nSample check (rows 151-160):")
for r in rows[150:160]:
    print(f"  {r['id']:4s} | {r['word']:25s} | {r['example_de']}")
