import csv

CSV_PATH = '/Users/mehrashojjat/Desktop/Works/MI/DL/word_data/quiz_csv/b1.csv'

# Batch 1: rows id 1–150
# Proper B1-level German example sentences reflecting each word's meaning
examples = {
    "1":   "Ich habe ein Magazin-Abo und bekomme es jeden Monat nach Hause.",
    "2":   "Der Akku meines Handys ist fast leer – ich muss es laden.",
    "3":   "Der Azubi lernt in einem Autohaus, wie man Autos repariert.",
    "4":   "Die Arztpraxis befindet sich im EG des Gebäudes.",
    "5":   "Das Baby schläft gerade ruhig in seinem Kinderbett.",
    "6":   "Sie hat einen Babysitter gesucht, der abends auf ihr Kind aufpasst.",
    "7":   "Die Band spielt heute Abend ein Konzert in der Stadthalle.",
    "8":   "Die Kinder hatten viel Spaß im Feriencamp.",
    "9":   "Das ist das übergeordnete Ziel unseres gemeinsamen Projekts.",
    "10":  "Sie benutzt ihr Smartphone täglich, um Nachrichten zu schreiben.",
    "11":  "Dieser Song läuft gerade überall im Radio.",
    "12":  "Das Hotel hat einen großen Swimmingpool im Garten.",
    "13":  "Die erste Aufgabe war einfach, aber die zweite war viel schwieriger.",
    "14":  "Bitte kreuzen Sie die richtige Antwort auf dem Bogen an.",
    "15":  "Schreiben Sie Ihre Antworten auf den Antwortbogen.",
    "16":  "Er hat eine Anzeige aufgegeben, weil er eine Wohnung sucht.",
    "17":  "Deine Antwort ist richtig – herzlichen Glückwunsch!",
    "18":  "Am Bahnhof kam eine Durchsage über die Verspätung des Zuges.",
    "19":  "Die Einleitung des Aufsatzes soll das Thema kurz vorstellen.",
    "20":  "Der Lehrer hat die Grafik auf einer Folie an die Wand projiziert.",
    "21":  "Bei der Prüfung sind keine Hilfsmittel wie Wörterbücher erlaubt.",
    "22":  "Ich habe einen Kommentar unter dem Artikel hinterlassen.",
    "23":  "Er hat das mathematische Problem schnell und richtig gelöst.",
    "24":  "Der Moderator hat die Diskussion sehr professionell geleitet.",
    "25":  "Im nächsten Modul des Kurses lernen wir Grammatik.",
    "26":  "Sie hat eine tolle Präsentation über Klimawandel gehalten.",
    "27":  "Für jede richtige Antwort bekommst du einen Punkt.",
    "28":  "Die Rückmeldung der Lehrerin war sehr hilfreich für mich.",
    "29":  "Der Text hat eine klare und logische Struktur.",
    "30":  "Ein guter Textaufbau besteht aus Einleitung, Hauptteil und Schluss.",
    "31":  "Er hat die handschriftlichen Notizen auf den Computer übertragen.",
    "32":  "Ordne bitte die Definitionen den richtigen Wörtern zu.",
    "33":  "Österreich ist ein schönes Land in Mitteleuropa.",
    "34":  "Jedes Jahr besuchen Millionen von Touristen Österreich.",
    "35":  "Hamburg liegt im Norden Deutschlands direkt an der Elbe.",
    "36":  "Dresden liegt im Osten Deutschlands nahe der tschechischen Grenze.",
    "37":  "Berlin liegt nordöstlich von Leipzig.",
    "38":  "In Süddeutschland liegt das bekannte Bundesland Bayern.",
    "39":  "Er ist Deutscher und lebt seit vielen Jahren in Berlin.",
    "40":  "In Europa gibt es viele verschiedene Sprachen und Kulturen.",
    "41":  "Sie ist Europäerin und reist gerne durch verschiedene Länder.",
    "42":  "Das ist ein wichtiges europäisches Thema.",
    "43":  "Der Österreicher kommt aus Wien und spricht sehr gut Deutsch.",
    "44":  "Die Türkei liegt zwischen Europa und Asien.",
    "45":  "Die Ukraine ist das flächenmäßig größte Land innerhalb Europas.",
    "46":  "Der Ukrainer hat in Deutschland eine neue Arbeit gefunden.",
    "47":  "Der Bund ist für dieses Gesetz zuständig, nicht die Länder.",
    "48":  "Der Bundeskanzler hat heute eine wichtige Rede im Parlament gehalten.",
    "49":  "Die Bundeskanzlerin hat viele wichtige Entscheidungen für das Land getroffen.",
    "50":  "Der Bundespräsident empfängt heute ausländische Staatsgäste.",
    "51":  "Die Bundespräsidentin hat eine Rede über Demokratie und Freiheit gehalten.",
    "52":  "Der Bürgermeister hat den neuen Stadtpark feierlich eröffnet.",
    "53":  "Die Bürgermeisterin setzt sich stark für bessere Schulen in der Stadt ein.",
    "54":  "Die Ministerin hat das neue Bildungsprogramm im Parlament vorgestellt.",
    "55":  "Das Parlament hat gestern über das neue Steuergesetz abgestimmt.",
    "56":  "Sie ist seit Jahren aktives Mitglied einer politischen Partei.",
    "57":  "Der Staat investiert mehr Geld in Bildung und Gesundheit.",
    "58":  "Das Bankwesen hat sich durch die Digitalisierung stark verändert.",
    "59":  "Im Zoo haben wir einem Affen beim Klettern zugeschaut.",
    "60":  "Der Bär ist das Wappentier der Hauptstadt Berlin.",
    "61":  "Im Frühling blühen überall bunte Blumen in den Parks.",
    "62":  "Im Sommer verbringen wir unsere Ferien am Meer.",
    "63":  "Im Januar ist es in Deutschland oft sehr kalt und es schneit.",
    "64":  "Der Februar ist der kürzeste Monat des Jahres.",
    "65":  "An diesem Tag war das Wetter besonders schön und sonnig.",
    "66":  "Am Morgen trinke ich immer eine Tasse Kaffee.",
    "67":  "Um Mittag treffen wir uns in der Kantine zum Essen.",
    "68":  "Er brauchte nur eine Sekunde, um die richtige Antwort zu geben.",
    "69":  "Das Meeting dauert maximal fünfzehn Minuten.",
    "70":  "Der Bus fährt stündlich vom Hauptbahnhof ab.",
    "71":  "An Wochentagen beginnt mein Arbeitstag um acht Uhr morgens.",
    "72":  "Am Wochenende schlafen wir gerne etwas länger.",
    "73":  "Am Dienstag habe ich einen Termin beim Zahnarzt.",
    "74":  "Mittwoch ist in unserer Stadt ein Markttag.",
    "75":  "Das Kind kann schon bis zehn zählen.",
    "76":  "Das Glas ist erst halb voll.",
    "77":  "Nach dem Abitur möchte sie Medizin studieren.",
    "78":  "Wir haben abgemacht, uns morgen um drei Uhr zu treffen.",
    "79":  "Er hat im letzten Jahr durch Sport fünf Kilo abgenommen.",
    "80":  "Ich habe den Newsletter abonniert, um keine Angebote zu verpassen.",
    "81":  "Das Abonnement für die Zeitung kostet zwanzig Euro im Monat.",
    "82":  "Sie musste das Treffen leider absagen, weil sie krank war.",
    "83":  "Nach dem Abschluss des Studiums hat er eine gute Stelle gefunden.",
    "84":  "Lesen Sie bitte den zweiten Abschnitt des Textes sorgfältig.",
    "85":  "Ich kann den Absender des Briefes nicht erkennen.",
    "86":  "Die Absenderin hat keine Rücksendeadresse auf dem Umschlag angegeben.",
    "87":  "Es war keine Absicht – das war ein einfaches Versehen.",
    "88":  "Das Ergebnis ist absolut korrekt.",
    "89":  "Das Team hat gemeinsam über den neuen Plan abgestimmt.",
    "90":  "Er arbeitet seit drei Jahren in der Personalabteilung.",
    "91":  "Der Hausmeister hat den Wasserschaden im Keller repariert.",
    "92":  "Die Hausmeisterin kümmert sich um das gesamte Gebäude.",
    "93":  "Die Wirtschaft geht derzeit stark abwärts.",
    "94":  "Nach dem Abendessen habe ich das Geschirr abgewaschen.",
    "95":  "Er war heute aus Krankheitsgründen abwesend.",
    "96":  "Du solltest mehr auf deine Gesundheit achten.",
    "97":  "Der Zug fährt in fünf Minuten ab – beeil dich!",
    "98":  "An der zweiten Kreuzung bitte rechts abbiegen.",
    "99":  "Schauen Sie sich die Abbildung auf Seite zwölf genau an.",
    "100": "Die Reise durch Südamerika war ein echtes Abenteuer.",
    "101": "Das Wetter war schlecht, aber wir haben trotzdem viel Spaß gehabt.",
    "102": "Unser Zug fährt um acht Uhr dreißig ab.",
    "103": "Die Abfahrt des Busses ist um neun Uhr vom Hauptbahnhof.",
    "104": "Bitte werfen Sie den Abfall in den Mülleimer und nicht auf die Straße.",
    "105": "Der Abfalleimer in der Küche ist voll und muss geleert werden.",
    "106": "Der Erfolg des Projekts hängt von der guten Vorbereitung ab.",
    "107": "Manche Menschen sind sehr abhängig von ihrem Smartphone.",
    "108": "Ich muss heute noch Geld am Automaten abheben.",
    "109": "Kannst du mich bitte um drei Uhr vom Bahnhof abholen?",
    "110": "Sie macht jeden Tag ihre Hausaufgaben, bevor sie fernsieht.",
    "111": "Er hat seine Aufgaben schon gemacht und kann jetzt spielen.",
    "112": "Sein Antrag auf ein Visum wurde leider abgelehnt.",
    "113": "Bei der Feier gab es viele verschiedene Getränke zur Auswahl.",
    "114": "Sie möchte abnehmen und geht jetzt zweimal pro Woche ins Fitnessstudio.",
    "115": "Ich bin müde, weil ich letzte Nacht nicht gut geschlafen habe.",
    "116": "Es ist wichtig, jeden Tag genug Wasser zu trinken.",
    "117": "Die Schülerin war bei der Prüfung abwesend, weil sie krank war.",
    "118": "Vergiss nicht, die Haustür abzuschließen, wenn du das Haus verlässt.",
    "119": "Dieses Gerät hilft mir dabei, die Raumtemperatur zu regulieren.",
    "120": "Er erzählt immer teure Geschichten, die kaum jemand glauben kann.",
    "121": "Ich bin ganz sicher, dass er heute noch kommt.",
    "122": "Es hat geregnet, trotzdem sind wir spazieren gegangen.",
    "123": "Wir sind heute früh aufgestanden, weil wir einen langen Tag hatten.",
    "124": "Wir gehen heute Abend zusammen ins Restaurant.",
    "125": "Leider kann ich heute nicht zu deiner Party kommen.",
    "126": "Ich warte hier, bis du von der Arbeit zurückkommst.",
    "127": "Ich gehe zum Supermarkt, um frisches Brot zu kaufen.",
    "128": "Die Fabrik hat den Fluss durch ihre Abwässer stark verschmutzt.",
    "129": "Kinder sollten nicht zu abhängig von Computerspielen sein.",
    "130": "Ich fahre jeden Tag mit meinem Fahrrad zur Arbeit.",
    "131": "Er wurde pünktlich vom Flughafen abgeholt.",
    "132": "Sie hat das Abitur mit einer sehr guten Note bestanden.",
    "133": "Lass uns abmachen, wann wir uns das nächste Mal treffen.",
    "134": "Durch Sport und gesunde Ernährung kann man gut abnehmen.",
    "135": "Haben Sie schon unseren kostenlosen Newsletter abonniert?",
    "136": "Das Abonnement läuft noch bis Ende des Jahres.",
    "137": "Er hat das Konzert wegen einer Krankheit kurzfristig abgesagt.",
    "138": "Zum Abschluss des Kurses gibt es ein gemeinsames Abschlussfest.",
    "139": "Der dritte Abschnitt des Textes enthält die wichtigsten Informationen.",
    "140": "Ohne Absender weiß ich nicht, von wem dieser Brief kommt.",
    "141": "Die Absenderin der E-Mail war ihre Kollegin Frau Müller.",
    "142": "Sie hat das mit guter Absicht getan, auch wenn es falsch war.",
    "143": "Ich stimme absolut mit deiner Meinung überein.",
    "144": "Wir stimmen gemeinsam über den nächsten Arbeitstermin ab.",
    "145": "Die Marketingabteilung sucht neue kreative Mitarbeiter.",
    "146": "Der Wanderweg führt steil abwärts in das Tal.",
    "147": "Er wäscht jeden Abend nach dem Essen das Geschirr ab.",
    "148": "Sie war bei der Sitzung abwesend und hat die Notizen später bekommen.",
    "149": "Bitte achten Sie auf die Sicherheitshinweise des Lehrers.",
    "150": "Das Flugzeug hebt um zehn Uhr ab und landet in Wien.",
}

with open(CSV_PATH, newline='', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    fieldnames = reader.fieldnames
    rows = list(reader)

updated = 0
for r in rows:
    if r['id'] in examples:
        r['example_de'] = examples[r['id']]
        updated += 1

with open(CSV_PATH, 'w', newline='', encoding='utf-8') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

filled = sum(1 for r in rows if r['example_de'].strip())
print(f"Updated {updated} rows. Total filled: {filled} / {len(rows)}")
print("\nSample check (first 10):")
for r in rows[:10]:
    print(f"  {r['id']:3s} | {r['word']:20s} | {r['example_de']}")
